part of '../device_snapshot.dart';

/// Phase-modulation (FM) synth device snapshot.
class PhaseModSynthDeviceSnapshot extends DeviceSnapshot implements VirtualStripHostSnapshot {
  @override
  final List<DeviceSnapshot> audioFxDevices;
  @override
  final List<DeviceSnapshot> noteFxDevices;
  const PhaseModSynthDeviceSnapshot({
    required super.id,
    required super.gain,
    required super.pan,
    required super.bypassed,
    required super.meterGainReductionDb,
    required super.meterInputLevel,
    required this.pmOp1Ratio,
    required this.pmOp1Fine,
    required this.pmOp1Level,
    required this.pmOp1Wave,
    required this.pmOp1Attack,
    required this.pmOp1Decay,
    required this.pmOp1Sustain,
    required this.pmOp1Release,
    required this.pmOp1VelSense,
    required this.pmOp1KeyTrack,
    required this.pmOp2Ratio,
    required this.pmOp2Fine,
    required this.pmOp2Level,
    required this.pmOp2Wave,
    required this.pmOp2Attack,
    required this.pmOp2Decay,
    required this.pmOp2Sustain,
    required this.pmOp2Release,
    required this.pmOp2VelSense,
    required this.pmOp2KeyTrack,
    required this.pmOp3Ratio,
    required this.pmOp3Fine,
    required this.pmOp3Level,
    required this.pmOp3Wave,
    required this.pmOp3Attack,
    required this.pmOp3Decay,
    required this.pmOp3Sustain,
    required this.pmOp3Release,
    required this.pmOp3VelSense,
    required this.pmOp3KeyTrack,
    required this.pmOp4Ratio,
    required this.pmOp4Fine,
    required this.pmOp4Level,
    required this.pmOp4Wave,
    required this.pmOp4Attack,
    required this.pmOp4Decay,
    required this.pmOp4Sustain,
    required this.pmOp4Release,
    required this.pmOp4VelSense,
    required this.pmOp4KeyTrack,
    required this.pmAlgoIndex,
    required this.pmFeedback,
    required this.pmUnisonVoices,
    required this.pmUnisonDetune,
    required this.pmGlide,
    required this.pmMono,
    required this.pmLegato,
    required this.pmMasterVol,
    required this.pmLfoRate,
    required this.pmLfoShape,
    required this.pmLfoAmount,
    required this.pmLfoDest,
    required this.pmVibratoDepth,
    required this.pmVibratoRate,
    required this.filterCutoff,
    required this.filterQ,
    required this.filterMode,
    required this.filterEnvAmount,
    required this.filterAttack,
    required this.filterDecay,
    required this.filterSustain,
    required this.filterRelease,
    required this.filterKeyTrack,
    required this.attack,
    required this.decay,
    required this.sustain,
    required this.release,
    this.audioFxDevices = const [],
    this.noteFxDevices = const [],
  }) : super(type: 'phase_mod_synth');

  final double pmOp1Ratio, pmOp1Fine, pmOp1Level, pmOp1Wave, pmOp1Attack, pmOp1Decay, pmOp1Sustain, pmOp1Release, pmOp1VelSense, pmOp1KeyTrack;

  final double pmOp2Ratio, pmOp2Fine, pmOp2Level, pmOp2Wave, pmOp2Attack, pmOp2Decay, pmOp2Sustain, pmOp2Release, pmOp2VelSense, pmOp2KeyTrack;

  final double pmOp3Ratio, pmOp3Fine, pmOp3Level, pmOp3Wave, pmOp3Attack, pmOp3Decay, pmOp3Sustain, pmOp3Release, pmOp3VelSense, pmOp3KeyTrack;

  final double pmOp4Ratio, pmOp4Fine, pmOp4Level, pmOp4Wave, pmOp4Attack, pmOp4Decay, pmOp4Sustain, pmOp4Release, pmOp4VelSense, pmOp4KeyTrack;

  final int pmAlgoIndex;
  final double pmFeedback, pmUnisonVoices, pmUnisonDetune, pmGlide, pmMono, pmLegato, pmMasterVol, pmLfoRate, pmLfoShape, pmLfoAmount;
  final int pmLfoDest;
  final double pmVibratoDepth, pmVibratoRate;

  final double filterCutoff, filterQ;
  final int filterMode;
  final double filterEnvAmount, filterAttack, filterDecay, filterSustain, filterRelease, filterKeyTrack;

  final double attack, decay, sustain, release;

  factory PhaseModSynthDeviceSnapshot.fromMap(Map<dynamic, dynamic> map) => _phaseModSynthFromMap(map);

  @override
  PhaseModSynthDeviceSnapshot copyWith({
    String? id,
    String? type,
    double? gain,
    double? pan,
    bool? bypassed,
    double? meterGainReductionDb,
    double? meterInputLevel,
    double? pmOp1Ratio,
    double? pmOp1Fine,
    double? pmOp1Level,
    double? pmOp1Wave,
    double? pmOp1Attack,
    double? pmOp1Decay,
    double? pmOp1Sustain,
    double? pmOp1Release,
    double? pmOp1VelSense,
    double? pmOp1KeyTrack,
    double? pmOp2Ratio,
    double? pmOp2Fine,
    double? pmOp2Level,
    double? pmOp2Wave,
    double? pmOp2Attack,
    double? pmOp2Decay,
    double? pmOp2Sustain,
    double? pmOp2Release,
    double? pmOp2VelSense,
    double? pmOp2KeyTrack,
    double? pmOp3Ratio,
    double? pmOp3Fine,
    double? pmOp3Level,
    double? pmOp3Wave,
    double? pmOp3Attack,
    double? pmOp3Decay,
    double? pmOp3Sustain,
    double? pmOp3Release,
    double? pmOp3VelSense,
    double? pmOp3KeyTrack,
    double? pmOp4Ratio,
    double? pmOp4Fine,
    double? pmOp4Level,
    double? pmOp4Wave,
    double? pmOp4Attack,
    double? pmOp4Decay,
    double? pmOp4Sustain,
    double? pmOp4Release,
    double? pmOp4VelSense,
    double? pmOp4KeyTrack,
    int? pmAlgoIndex,
    double? pmFeedback,
    double? pmUnisonVoices,
    double? pmUnisonDetune,
    double? pmGlide,
    double? pmMono,
    double? pmLegato,
    double? pmMasterVol,
    double? pmLfoRate,
    double? pmLfoShape,
    double? pmLfoAmount,
    int? pmLfoDest,
    double? pmVibratoDepth,
    double? pmVibratoRate,
    double? filterCutoff,
    double? filterQ,
    int? filterMode,
    double? filterEnvAmount,
    double? filterAttack,
    double? filterDecay,
    double? filterSustain,
    double? filterRelease,
    double? filterKeyTrack,
    double? attack,
    double? decay,
    double? sustain,
    double? release,
    List<DeviceSnapshot>? audioFxDevices,
    List<DeviceSnapshot>? noteFxDevices,
  }) {
    return PhaseModSynthDeviceSnapshot(
      id: id ?? this.id,
      gain: gain ?? this.gain,
      pan: pan ?? this.pan,
      bypassed: bypassed ?? this.bypassed,
      meterGainReductionDb: meterGainReductionDb ?? this.meterGainReductionDb,
      meterInputLevel: meterInputLevel ?? this.meterInputLevel,
      pmOp1Ratio: pmOp1Ratio ?? this.pmOp1Ratio,
      pmOp1Fine: pmOp1Fine ?? this.pmOp1Fine,
      pmOp1Level: pmOp1Level ?? this.pmOp1Level,
      pmOp1Wave: pmOp1Wave ?? this.pmOp1Wave,
      pmOp1Attack: pmOp1Attack ?? this.pmOp1Attack,
      pmOp1Decay: pmOp1Decay ?? this.pmOp1Decay,
      pmOp1Sustain: pmOp1Sustain ?? this.pmOp1Sustain,
      pmOp1Release: pmOp1Release ?? this.pmOp1Release,
      pmOp1VelSense: pmOp1VelSense ?? this.pmOp1VelSense,
      pmOp1KeyTrack: pmOp1KeyTrack ?? this.pmOp1KeyTrack,
      pmOp2Ratio: pmOp2Ratio ?? this.pmOp2Ratio,
      pmOp2Fine: pmOp2Fine ?? this.pmOp2Fine,
      pmOp2Level: pmOp2Level ?? this.pmOp2Level,
      pmOp2Wave: pmOp2Wave ?? this.pmOp2Wave,
      pmOp2Attack: pmOp2Attack ?? this.pmOp2Attack,
      pmOp2Decay: pmOp2Decay ?? this.pmOp2Decay,
      pmOp2Sustain: pmOp2Sustain ?? this.pmOp2Sustain,
      pmOp2Release: pmOp2Release ?? this.pmOp2Release,
      pmOp2VelSense: pmOp2VelSense ?? this.pmOp2VelSense,
      pmOp2KeyTrack: pmOp2KeyTrack ?? this.pmOp2KeyTrack,
      pmOp3Ratio: pmOp3Ratio ?? this.pmOp3Ratio,
      pmOp3Fine: pmOp3Fine ?? this.pmOp3Fine,
      pmOp3Level: pmOp3Level ?? this.pmOp3Level,
      pmOp3Wave: pmOp3Wave ?? this.pmOp3Wave,
      pmOp3Attack: pmOp3Attack ?? this.pmOp3Attack,
      pmOp3Decay: pmOp3Decay ?? this.pmOp3Decay,
      pmOp3Sustain: pmOp3Sustain ?? this.pmOp3Sustain,
      pmOp3Release: pmOp3Release ?? this.pmOp3Release,
      pmOp3VelSense: pmOp3VelSense ?? this.pmOp3VelSense,
      pmOp3KeyTrack: pmOp3KeyTrack ?? this.pmOp3KeyTrack,
      pmOp4Ratio: pmOp4Ratio ?? this.pmOp4Ratio,
      pmOp4Fine: pmOp4Fine ?? this.pmOp4Fine,
      pmOp4Level: pmOp4Level ?? this.pmOp4Level,
      pmOp4Wave: pmOp4Wave ?? this.pmOp4Wave,
      pmOp4Attack: pmOp4Attack ?? this.pmOp4Attack,
      pmOp4Decay: pmOp4Decay ?? this.pmOp4Decay,
      pmOp4Sustain: pmOp4Sustain ?? this.pmOp4Sustain,
      pmOp4Release: pmOp4Release ?? this.pmOp4Release,
      pmOp4VelSense: pmOp4VelSense ?? this.pmOp4VelSense,
      pmOp4KeyTrack: pmOp4KeyTrack ?? this.pmOp4KeyTrack,
      pmAlgoIndex: pmAlgoIndex ?? this.pmAlgoIndex,
      pmFeedback: pmFeedback ?? this.pmFeedback,
      pmUnisonVoices: pmUnisonVoices ?? this.pmUnisonVoices,
      pmUnisonDetune: pmUnisonDetune ?? this.pmUnisonDetune,
      pmGlide: pmGlide ?? this.pmGlide,
      pmMono: pmMono ?? this.pmMono,
      pmLegato: pmLegato ?? this.pmLegato,
      pmMasterVol: pmMasterVol ?? this.pmMasterVol,
      pmLfoRate: pmLfoRate ?? this.pmLfoRate,
      pmLfoShape: pmLfoShape ?? this.pmLfoShape,
      pmLfoAmount: pmLfoAmount ?? this.pmLfoAmount,
      pmLfoDest: pmLfoDest ?? this.pmLfoDest,
      pmVibratoDepth: pmVibratoDepth ?? this.pmVibratoDepth,
      pmVibratoRate: pmVibratoRate ?? this.pmVibratoRate,
      filterCutoff: filterCutoff ?? this.filterCutoff,
      filterQ: filterQ ?? this.filterQ,
      filterMode: filterMode ?? this.filterMode,
      filterEnvAmount: filterEnvAmount ?? this.filterEnvAmount,
      filterAttack: filterAttack ?? this.filterAttack,
      filterDecay: filterDecay ?? this.filterDecay,
      filterSustain: filterSustain ?? this.filterSustain,
      filterRelease: filterRelease ?? this.filterRelease,
      filterKeyTrack: filterKeyTrack ?? this.filterKeyTrack,
      attack: attack ?? this.attack,
      decay: decay ?? this.decay,
      sustain: sustain ?? this.sustain,
      release: release ?? this.release,
      audioFxDevices: audioFxDevices ?? this.audioFxDevices,
      noteFxDevices: noteFxDevices ?? this.noteFxDevices,
    );
  }

  @override
  PhaseModSynthDeviceSnapshot withParameter(String parameterId, double value) => _withParameterImpl(parameterId, value);
}
