part of '../device_snapshot.dart';

extension PhaseModSynthDeviceSnapshotWithparameterimplOperation on PhaseModSynthDeviceSnapshot {
PhaseModSynthDeviceSnapshot _withParameterImpl(
    String parameterId,
    double value,
  ) {
    return switch (parameterId) {
      'gain' => copyWith(gain: value),
      'pan' => copyWith(pan: value),
      'bypass' => copyWith(bypassed: value >= 0.5),
      'pmOp1Ratio' => copyWith(pmOp1Ratio: value),
      'pmOp1Fine' => copyWith(pmOp1Fine: value),
      'pmOp1Level' => copyWith(pmOp1Level: value),
      'pmOp1Wave' => copyWith(pmOp1Wave: value),
      'pmOp1Attack' => copyWith(pmOp1Attack: value),
      'pmOp1Decay' => copyWith(pmOp1Decay: value),
      'pmOp1Sustain' => copyWith(pmOp1Sustain: value),
      'pmOp1Release' => copyWith(pmOp1Release: value),
      'pmOp1VelSense' => copyWith(pmOp1VelSense: value),
      'pmOp1KeyTrack' => copyWith(pmOp1KeyTrack: value),
      'pmOp2Ratio' => copyWith(pmOp2Ratio: value),
      'pmOp2Fine' => copyWith(pmOp2Fine: value),
      'pmOp2Level' => copyWith(pmOp2Level: value),
      'pmOp2Wave' => copyWith(pmOp2Wave: value),
      'pmOp2Attack' => copyWith(pmOp2Attack: value),
      'pmOp2Decay' => copyWith(pmOp2Decay: value),
      'pmOp2Sustain' => copyWith(pmOp2Sustain: value),
      'pmOp2Release' => copyWith(pmOp2Release: value),
      'pmOp2VelSense' => copyWith(pmOp2VelSense: value),
      'pmOp2KeyTrack' => copyWith(pmOp2KeyTrack: value),
      'pmOp3Ratio' => copyWith(pmOp3Ratio: value),
      'pmOp3Fine' => copyWith(pmOp3Fine: value),
      'pmOp3Level' => copyWith(pmOp3Level: value),
      'pmOp3Wave' => copyWith(pmOp3Wave: value),
      'pmOp3Attack' => copyWith(pmOp3Attack: value),
      'pmOp3Decay' => copyWith(pmOp3Decay: value),
      'pmOp3Sustain' => copyWith(pmOp3Sustain: value),
      'pmOp3Release' => copyWith(pmOp3Release: value),
      'pmOp3VelSense' => copyWith(pmOp3VelSense: value),
      'pmOp3KeyTrack' => copyWith(pmOp3KeyTrack: value),
      'pmOp4Ratio' => copyWith(pmOp4Ratio: value),
      'pmOp4Fine' => copyWith(pmOp4Fine: value),
      'pmOp4Level' => copyWith(pmOp4Level: value),
      'pmOp4Wave' => copyWith(pmOp4Wave: value),
      'pmOp4Attack' => copyWith(pmOp4Attack: value),
      'pmOp4Decay' => copyWith(pmOp4Decay: value),
      'pmOp4Sustain' => copyWith(pmOp4Sustain: value),
      'pmOp4Release' => copyWith(pmOp4Release: value),
      'pmOp4VelSense' => copyWith(pmOp4VelSense: value),
      'pmOp4KeyTrack' => copyWith(pmOp4KeyTrack: value),
      'pmAlgoIndex' => copyWith(pmAlgoIndex: value.round()),
      'pmFeedback' => copyWith(pmFeedback: value),
      'pmUnisonVoices' => copyWith(pmUnisonVoices: value),
      'pmUnisonDetune' => copyWith(pmUnisonDetune: value),
      'pmGlide' => copyWith(pmGlide: value),
      'pmMono' => copyWith(pmMono: value),
      'pmLegato' => copyWith(pmLegato: value),
      'pmMasterVol' => copyWith(pmMasterVol: value),
      'pmLfoRate' => copyWith(pmLfoRate: value),
      'pmLfoShape' => copyWith(pmLfoShape: value),
      'pmLfoAmount' => copyWith(pmLfoAmount: value),
      'pmLfoDest' => copyWith(pmLfoDest: value.round()),
      'pmVibratoDepth' => copyWith(pmVibratoDepth: value),
      'pmVibratoRate' => copyWith(pmVibratoRate: value),
      'filterCutoff' => copyWith(filterCutoff: value),
      'filterQ' => copyWith(filterQ: value),
      'filterMode' => copyWith(filterMode: value.round().clamp(0, 5)),
      'filterEnvAmount' => copyWith(filterEnvAmount: value),
      'filterAttack' => copyWith(filterAttack: value),
      'filterDecay' => copyWith(filterDecay: value),
      'filterSustain' => copyWith(filterSustain: value),
      'filterRelease' => copyWith(filterRelease: value),
      'filterKeyTrack' => copyWith(filterKeyTrack: value),
      'attack' => copyWith(attack: value),
      'decay' => copyWith(decay: value),
      'sustain' => copyWith(sustain: value),
      'release' => copyWith(release: value),
      _ => this,
    };
  }
}
