part of '../device_snapshot.dart';

PhaseModSynthDeviceSnapshot _phaseModSynthFromMap(Map<dynamic, dynamic> map) {
  final params = map['parameters'] as Map<dynamic, dynamic>? ?? {};
  final outputPanel = map['outputPanel'] as Map<dynamic, dynamic>? ?? {};
  final meters = map['meters'] as Map<dynamic, dynamic>? ?? {};
  return PhaseModSynthDeviceSnapshot(
    id: map['id'] as String? ?? '',
    gain: (outputPanel['gain'] as num?)?.toDouble() ?? 1.0,
    pan: (outputPanel['pan'] as num?)?.toDouble() ?? 0.5,
    bypassed: readBypass(map['bypass']),
    meterGainReductionDb:
        (meters['gainReductionDb'] as num?)?.toDouble() ?? 0.0,
    meterInputLevel: (meters['inputLevel'] as num?)?.toDouble() ?? 0.0,
    pmOp1Ratio: (params['pmOp1Ratio'] as num?)?.toDouble() ?? 0.0625,
    pmOp1Fine: (params['pmOp1Fine'] as num?)?.toDouble() ?? 0.5,
    pmOp1Level: (params['pmOp1Level'] as num?)?.toDouble() ?? 0.8,
    pmOp1Wave: (params['pmOp1Wave'] as num?)?.toDouble() ?? 0.0,
    pmOp1Attack: (params['pmOp1Attack'] as num?)?.toDouble() ?? 0.01,
    pmOp1Decay: (params['pmOp1Decay'] as num?)?.toDouble() ?? 0.3,
    pmOp1Sustain: (params['pmOp1Sustain'] as num?)?.toDouble() ?? 0.8,
    pmOp1Release: (params['pmOp1Release'] as num?)?.toDouble() ?? 0.4,
    pmOp1VelSense: (params['pmOp1VelSense'] as num?)?.toDouble() ?? 1.0,
    pmOp1KeyTrack: (params['pmOp1KeyTrack'] as num?)?.toDouble() ?? 0.0,
    pmOp2Ratio: (params['pmOp2Ratio'] as num?)?.toDouble() ?? 0.4375,
    pmOp2Fine: (params['pmOp2Fine'] as num?)?.toDouble() ?? 0.5,
    pmOp2Level: (params['pmOp2Level'] as num?)?.toDouble() ?? 0.4,
    pmOp2Wave: (params['pmOp2Wave'] as num?)?.toDouble() ?? 0.0,
    pmOp2Attack: (params['pmOp2Attack'] as num?)?.toDouble() ?? 0.01,
    pmOp2Decay: (params['pmOp2Decay'] as num?)?.toDouble() ?? 0.3,
    pmOp2Sustain: (params['pmOp2Sustain'] as num?)?.toDouble() ?? 0.8,
    pmOp2Release: (params['pmOp2Release'] as num?)?.toDouble() ?? 0.4,
    pmOp2VelSense: (params['pmOp2VelSense'] as num?)?.toDouble() ?? 1.0,
    pmOp2KeyTrack: (params['pmOp2KeyTrack'] as num?)?.toDouble() ?? 0.0,
    pmOp3Ratio: (params['pmOp3Ratio'] as num?)?.toDouble() ?? 0.75,
    pmOp3Fine: (params['pmOp3Fine'] as num?)?.toDouble() ?? 0.5,
    pmOp3Level: (params['pmOp3Level'] as num?)?.toDouble() ?? 0.0,
    pmOp3Wave: (params['pmOp3Wave'] as num?)?.toDouble() ?? 0.0,
    pmOp3Attack: (params['pmOp3Attack'] as num?)?.toDouble() ?? 0.01,
    pmOp3Decay: (params['pmOp3Decay'] as num?)?.toDouble() ?? 0.3,
    pmOp3Sustain: (params['pmOp3Sustain'] as num?)?.toDouble() ?? 0.8,
    pmOp3Release: (params['pmOp3Release'] as num?)?.toDouble() ?? 0.4,
    pmOp3VelSense: (params['pmOp3VelSense'] as num?)?.toDouble() ?? 1.0,
    pmOp3KeyTrack: (params['pmOp3KeyTrack'] as num?)?.toDouble() ?? 0.0,
    pmOp4Ratio: (params['pmOp4Ratio'] as num?)?.toDouble() ?? 0.375,
    pmOp4Fine: (params['pmOp4Fine'] as num?)?.toDouble() ?? 0.5,
    pmOp4Level: (params['pmOp4Level'] as num?)?.toDouble() ?? 0.0,
    pmOp4Wave: (params['pmOp4Wave'] as num?)?.toDouble() ?? 0.0,
    pmOp4Attack: (params['pmOp4Attack'] as num?)?.toDouble() ?? 0.01,
    pmOp4Decay: (params['pmOp4Decay'] as num?)?.toDouble() ?? 0.3,
    pmOp4Sustain: (params['pmOp4Sustain'] as num?)?.toDouble() ?? 0.8,
    pmOp4Release: (params['pmOp4Release'] as num?)?.toDouble() ?? 0.4,
    pmOp4VelSense: (params['pmOp4VelSense'] as num?)?.toDouble() ?? 1.0,
    pmOp4KeyTrack: (params['pmOp4KeyTrack'] as num?)?.toDouble() ?? 0.0,
    pmAlgoIndex: (params['pmAlgoIndex'] as num?)?.toInt() ?? 0,
    pmFeedback: (params['pmFeedback'] as num?)?.toDouble() ?? 0.0,
    pmUnisonVoices: (params['pmUnisonVoices'] as num?)?.toDouble() ?? 0.0,
    pmUnisonDetune: (params['pmUnisonDetune'] as num?)?.toDouble() ?? 0.15,
    pmGlide: (params['pmGlide'] as num?)?.toDouble() ?? 0.0,
    pmMono: (params['pmMono'] as num?)?.toDouble() ?? 0.0,
    pmLegato: (params['pmLegato'] as num?)?.toDouble() ?? 0.0,
    pmMasterVol: (params['pmMasterVol'] as num?)?.toDouble() ?? 0.85,
    pmLfoRate: (params['pmLfoRate'] as num?)?.toDouble() ?? 0.2,
    pmLfoShape: (params['pmLfoShape'] as num?)?.toDouble() ?? 0.0,
    pmLfoAmount: (params['pmLfoAmount'] as num?)?.toDouble() ?? 0.0,
    pmLfoDest: (params['pmLfoDest'] as num?)?.toInt() ?? 0,
    pmVibratoDepth: (params['pmVibratoDepth'] as num?)?.toDouble() ?? 0.0,
    pmVibratoRate: (params['pmVibratoRate'] as num?)?.toDouble() ?? 0.3,
    filterCutoff: (params['filterCutoff'] as num?)?.toDouble() ?? 1.0,
    filterQ: (params['filterQ'] as num?)?.toDouble() ?? 0.35,
    filterMode: (params['filterMode'] as num?)?.toInt() ?? 0,
    filterEnvAmount: (params['filterEnvAmount'] as num?)?.toDouble() ?? 0.5,
    filterAttack: (params['filterAttack'] as num?)?.toDouble() ?? 0.05,
    filterDecay: (params['filterDecay'] as num?)?.toDouble() ?? 0.35,
    filterSustain: (params['filterSustain'] as num?)?.toDouble() ?? 0.4,
    filterRelease: (params['filterRelease'] as num?)?.toDouble() ?? 0.45,
    filterKeyTrack: (params['filterKeyTrack'] as num?)?.toDouble() ?? 0.0,
    attack: (params['attack'] as num?)?.toDouble() ?? 0.01,
    decay: (params['decay'] as num?)?.toDouble() ?? 0.3,
    sustain: (params['sustain'] as num?)?.toDouble() ?? 0.7,
    release: (params['release'] as num?)?.toDouble() ?? 0.4,
    audioFxDevices: parseDeviceList(map, 'audioFxDevices'),
    noteFxDevices: parseDeviceList(map, 'noteFxDevices'),
  );
}
