part of '../device_snapshot.dart';

extension SubtractiveSynthDeviceSnapshotWithparameterimplOperation on SubtractiveSynthDeviceSnapshot {
SubtractiveSynthDeviceSnapshot _withParameterImpl(
    String parameterId,
    double value,
  ) {
    return switch (parameterId) {
      'gain' => copyWith(gain: value),
      'pan' => copyWith(pan: value),
      'bypass' => copyWith(bypassed: value >= 0.5),
      'attack' => copyWith(attack: value),
      'decay' => copyWith(decay: value),
      'sustain' => copyWith(sustain: value),
      'release' => copyWith(release: value),
      'filterCutoff' => copyWith(filterCutoff: value),
      'filterQ' => copyWith(filterQ: value),
      'filterMode' => copyWith(filterMode: value.round().clamp(0, 5)),
      'osc1Shape' => copyWith(osc1Shape: value.clamp(0.0, 1.0)),
      'osc2Shape' => copyWith(osc2Shape: value.clamp(0.0, 1.0)),
      'osc1Octave' => copyWith(osc1Octave: value),
      'osc1Semi' => copyWith(osc1Semi: value),
      'osc1Detune' => copyWith(osc1Detune: value),
      'osc2Octave' => copyWith(osc2Octave: value),
      'osc2Semi' => copyWith(osc2Semi: value),
      'osc2Detune' => copyWith(osc2Detune: value),
      'oscMix' => copyWith(oscMix: value.clamp(0.0, 1.0)),
      'osc1Sync' => copyWith(osc1Sync: value.clamp(0.0, 1.0)),
      'osc2Sync' => copyWith(osc2Sync: value.clamp(0.0, 1.0)),
      'noiseLevel' => copyWith(noiseLevel: value),
      'oscMixMode' => copyWith(oscMixMode: value.round().clamp(0, 4)),
      'unisonVoices' => copyWith(unisonVoices: value),
      'unisonDetune' => copyWith(unisonDetune: value),
      'filterEnvAmount' => copyWith(filterEnvAmount: value),
      'filterAttack' => copyWith(filterAttack: value),
      'filterDecay' => copyWith(filterDecay: value),
      'filterSustain' => copyWith(filterSustain: value),
      'filterRelease' => copyWith(filterRelease: value),
      'glideMs' => copyWith(glideMs: value),
      'velocitySensitivity' => copyWith(velocitySensitivity: value),
      'preHpCutoff' => copyWith(preHpCutoff: value),
      'preHpRes' => copyWith(preHpRes: value),
      'preDrive' => copyWith(preDrive: value),
      'mixFeedback' => copyWith(mixFeedback: value),
      'globalPitch' => copyWith(globalPitch: value),
      'filterKeyTrack' => copyWith(filterKeyTrack: value),
      'filterDrive' => copyWith(filterDrive: value),
      'filterShaper' => copyWith(filterShaper: value),
      'filterFm' => copyWith(filterFm: value),
      'filterShaperMode' => copyWith(filterShaperMode: value.round().clamp(0, 3)),
      'synthLegato' => copyWith(synthLegato: value >= 0.5 ? 1.0 : 0.0),
      'synthMono' => copyWith(synthMono: value >= 0.5 ? 1.0 : 0.0),
      _ => this,
    };
  }
}
