part of 'chord_rhythm_catalog.dart';

const chordRhythmPresetList = <ChordRhythmPreset>[
  // Electronic / EDM
  ChordRhythmPreset(
    id: 'edm_big_room',
    subgenreId: 'elec_edm',
    label: 'Big-room hits',
    cells: [1, -1, 1, -1],
  ),
  ChordRhythmPreset(
    id: 'edm_pump',
    subgenreId: 'elec_edm',
    label: 'Pump L-L-S-S',
    cells: [2, 2, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'edm_build',
    subgenreId: 'elec_edm',
    label: 'Build (short×4)',
    cells: [1, 1, 1, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'edm_festival',
    subgenreId: 'elec_edm',
    label: 'Festival stabs',
    cells: [1, -1, 1, -1, 1, -1, 1, -1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'edm_drop',
    subgenreId: 'elec_edm',
    label: 'Drop punches',
    cells: [2, -1, 2, -1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'edm_sidechain',
    subgenreId: 'elec_edm',
    label: 'Sidechain gaps',
    cells: [-1, 1, -1, 1, -1, 1, -1, 1],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'edm_anthem',
    subgenreId: 'elec_edm',
    label: 'Anthem hits',
    cells: [3, 1, 3, 1],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'edm_double',
    subgenreId: 'elec_edm',
    label: 'Double-time stabs',
    cells: [1, 1, -1, 1, 1, -1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'edm_tresillo',
    subgenreId: 'elec_edm',
    label: 'Tresillo pump',
    cells: [2, 1, 1, 2, 1, 1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'edm_riser',
    subgenreId: 'elec_edm',
    label: 'Riser gaps',
    cells: [1, -2, 1, -2, 1, -2, 1, -2],
    gate: 0.65,
  ),

  // Trance
  ChordRhythmPreset(
    id: 'trance_gate8',
    subgenreId: 'elec_trance',
    label: 'Gated 1/8',
    cells: [1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.55,
  ),
  ChordRhythmPreset(
    id: 'trance_offbeat',
    subgenreId: 'elec_trance',
    label: 'Offbeat trance',
    cells: [-1, 1, -1, 1, -1, 1, -1, 1],
  ),
  ChordRhythmPreset(
    id: 'trance_roll16',
    subgenreId: 'elec_trance',
    label: 'Rolling 16ths',
    cells: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.65,
  ),
  ChordRhythmPreset(
    id: 'trance_break',
    subgenreId: 'elec_trance',
    label: 'Breakdown hold',
    cells: [4, -2, 4, -2],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'trance_supersaw',
    subgenreId: 'elec_trance',
    label: 'Supersaw pulse',
    cells: [1, -1, 1, 1, -1, 1, -1, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'trance_uplift',
    subgenreId: 'elec_trance',
    label: 'Uplifter swell',
    cells: [2, 2, 1, 1, 1, 1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'trance_tension',
    subgenreId: 'elec_trance',
    label: 'Tension gates',
    cells: [1, 1, 1, 1, -4],
    gate: 0.5,
  ),
  ChordRhythmPreset(
    id: 'trance_release',
    subgenreId: 'elec_trance',
    label: 'Release hits',
    cells: [2, -2, 1, 1, 1, 1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'trance_pluck',
    subgenreId: 'elec_trance',
    label: 'Pluck accents',
    cells: [1, -1, -1, 1, 1, -1, -1, 1],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'trance_euphoric',
    subgenreId: 'elec_trance',
    label: 'Euphoric stagger',
    cells: [3, 3, 2, 2],
    gate: 0.8,
  ),

  // Techno
  ChordRhythmPreset(
    id: 'techno_drive16',
    subgenreId: 'elec_techno',
    label: 'Driving 16ths',
    cells: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.5,
  ),
  ChordRhythmPreset(
    id: 'techno_sparse',
    subgenreId: 'elec_techno',
    label: 'Sparse offbeat',
    cells: [-3, 1, -2, 1, -3, 1, -2, 1],
  ),
  ChordRhythmPreset(
    id: 'techno_hypno',
    subgenreId: 'elec_techno',
    label: 'Hypnotic pulse',
    cells: [1, -1, 1, -1, 1, -1, 1, -1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'techno_industrial',
    subgenreId: 'elec_techno',
    label: 'Industrial chop',
    cells: [1, 1, -2, 1, -1, 1, 1, -2],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'techno_min2',
    subgenreId: 'elec_techno',
    label: 'Minimal 2-hit',
    cells: [4, -4, 4, -4],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'techno_dark',
    subgenreId: 'elec_techno',
    label: 'Dark syncopation',
    cells: [-1, 1, -1, 1, 1, -1, -1, 1],
    gate: 0.65,
  ),
  ChordRhythmPreset(
    id: 'techno_roll',
    subgenreId: 'elec_techno',
    label: 'Rolling pulse',
    cells: [1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1],
    gate: 0.55,
  ),
  ChordRhythmPreset(
    id: 'techno_strip',
    subgenreId: 'elec_techno',
    label: 'Stripped down',
    cells: [2, -6, 2, -6],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'techno_acid',
    subgenreId: 'elec_techno',
    label: 'Acid pulse',
    cells: [1, 1, -1, -1, 1, 1, -1, -1],
    gate: 0.55,
  ),
  ChordRhythmPreset(
    id: 'techno_peak',
    subgenreId: 'elec_techno',
    label: 'Peak sparse',
    cells: [-2, 1, -4, 1, -2, 1, -4],
    gate: 0.65,
  ),

  // DnB
  ChordRhythmPreset(
    id: 'dnb_halftime',
    subgenreId: 'elec_dnb',
    label: 'Half-time stabs',
    cells: [2, -2, 2, -2],
  ),
  ChordRhythmPreset(
    id: 'dnb_chop',
    subgenreId: 'elec_dnb',
    label: 'Chop L-S-S-L',
    cells: [2, 1, 1, 2],
  ),
  ChordRhythmPreset(
    id: 'dnb_roll',
    subgenreId: 'elec_dnb',
    label: 'Rolling 1/8',
    cells: [1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'dnb_amen',
    subgenreId: 'elec_dnb',
    label: 'Amen syncopation',
    cells: [1, -1, 1, 1, -1, 1, -1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'dnb_liquid',
    subgenreId: 'elec_dnb',
    label: 'Liquid hold',
    cells: [3, -1, 2, -2],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'dnb_neuro',
    subgenreId: 'elec_dnb',
    label: 'Neuro punch',
    cells: [1, 1, -1, 1, 1, -1, 1, -2],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'dnb_reese',
    subgenreId: 'elec_dnb',
    label: 'Reese stab',
    cells: [2, -1, 2, -1, 1, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'dnb_switch',
    subgenreId: 'elec_dnb',
    label: 'Switch-up',
    cells: [4, 1, 1, 1, -2, 1, 1, 1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'dnb_jump',
    subgenreId: 'elec_dnb',
    label: 'Jump-up stabs',
    cells: [1, -1, 1, 1, 1, -2],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'dnb_atmos',
    subgenreId: 'elec_dnb',
    label: 'Atmos swell',
    cells: [4, -3, 1, 1, 1, 1],
    gate: 0.85,
  ),

  // House classic
  ChordRhythmPreset(
    id: 'house_offbeat_ands',
    subgenreId: 'house_classic',
    label: 'Offbeat “ands”',
    cells: [-1, 1, -1, 1, -1, 1, -1, 1],
  ),
  ChordRhythmPreset(
    id: 'house_classic_16',
    subgenreId: 'house_classic',
    label: 'Classic stab 16ths',
    cells: [-2, 1, -3, 1, -2, 1, -3, 1],
  ),
  ChordRhythmPreset(
    id: 'house_disco',
    subgenreId: 'house_classic',
    label: 'Disco pump',
    cells: [1, -1, 1, -1, 2, -2],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'house_four',
    subgenreId: 'house_classic',
    label: 'Four-floor accents',
    cells: [1, 1, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'house_chicago',
    subgenreId: 'house_classic',
    label: 'Chicago stab',
    cells: [-1, 1, 1, -2, 1, -1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'house_jack',
    subgenreId: 'house_classic',
    label: 'Jack groove',
    cells: [1, 1, -1, 1, 1, -1, 1, -1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'house_filter',
    subgenreId: 'house_classic',
    label: 'Filter-pump gaps',
    cells: [-2, 1, -2, 1, -2, 1, -1, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'house_clap',
    subgenreId: 'house_classic',
    label: 'Handclap align',
    cells: [1, -1, -1, 1, 1, -1, -1, 1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'house_swing',
    subgenreId: 'house_classic',
    label: 'Swing offbeat',
    cells: [-1, 2, -2, 1, -1, 2, -2, 1],
    gate: 0.78,
  ),
  ChordRhythmPreset(
    id: 'house_late',
    subgenreId: 'house_classic',
    label: 'Late-night hold',
    cells: [3, -3, 2, -2],
    gate: 0.88,
  ),

  // Deep house
  ChordRhythmPreset(
    id: 'house_deep_soft',
    subgenreId: 'house_deep',
    label: 'Soft offbeat',
    cells: [-2, 1, -3, 1, -2, 1, -3, 1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'house_deep_sparse',
    subgenreId: 'house_deep',
    label: 'Sparse holds',
    cells: [3, -1, 2, -2],
  ),
  ChordRhythmPreset(
    id: 'house_deep_warm',
    subgenreId: 'house_deep',
    label: 'Warm pad hits',
    cells: [2, -2, 1, -1, 2, -2],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'house_deep_late',
    subgenreId: 'house_deep',
    label: 'Late night',
    cells: [-3, 1, -4, 1, -2, 1, -3],
    gate: 0.88,
  ),
  ChordRhythmPreset(
    id: 'house_deep_soul',
    subgenreId: 'house_deep',
    label: 'Soulful skip',
    cells: [-1, 2, -2, 1, -1, 2, -2],
    gate: 0.87,
  ),
  ChordRhythmPreset(
    id: 'house_deep_pocket',
    subgenreId: 'house_deep',
    label: 'Deep pocket',
    cells: [2, -3, 1, -2, 2, -3],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'house_deep_mellow',
    subgenreId: 'house_deep',
    label: 'Mellow 1/8',
    cells: [1, -1, 1, -2, 1, -1, 1, -2],
    gate: 0.92,
  ),
  ChordRhythmPreset(
    id: 'house_deep_breath',
    subgenreId: 'house_deep',
    label: 'Breath rests',
    cells: [4, -2, 3, -3],
    gate: 0.95,
  ),
  ChordRhythmPreset(
    id: 'house_deep_drift',
    subgenreId: 'house_deep',
    label: 'Drift offbeat',
    cells: [-4, 1, -3, 1, -4, 1, -3],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'house_deep_glow',
    subgenreId: 'house_deep',
    label: 'Glow stabs',
    cells: [1, -3, 1, -2, 1, -3, 1],
    gate: 0.92,
  ),

  // Tech house
  ChordRhythmPreset(
    id: 'house_tech_sync',
    subgenreId: 'house_tech',
    label: 'Syncopated 16ths',
    cells: [-1, 1, -2, 1, -1, 1, -3, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'house_tech_min',
    subgenreId: 'house_tech',
    label: 'Minimal stab',
    cells: [-3, 1, -4, 1, -3, 1, -3],
  ),
  ChordRhythmPreset(
    id: 'house_tech_tribal',
    subgenreId: 'house_tech',
    label: 'Tribal skip',
    cells: [1, -1, 1, -2, 1, -1, 1, -2],
    gate: 0.65,
  ),
  ChordRhythmPreset(
    id: 'house_tech_dark',
    subgenreId: 'house_tech',
    label: 'Dark offbeat',
    cells: [-2, 1, -1, 1, -3, 1, -1],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'house_tech_skip',
    subgenreId: 'house_tech',
    label: 'Groove skip',
    cells: [-1, 1, 1, -2, -1, 1, 1, -2],
    gate: 0.72,
  ),
  ChordRhythmPreset(
    id: 'house_tech_peak',
    subgenreId: 'house_tech',
    label: 'Peak-time',
    cells: [1, 1, -1, 1, 1, -1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'house_tech_wh',
    subgenreId: 'house_tech',
    label: 'Warehouse',
    cells: [1, -2, 1, -1, 1, -2, 1, -1],
    gate: 0.68,
  ),
  ChordRhythmPreset(
    id: 'house_tech_roll',
    subgenreId: 'house_tech',
    label: 'Rolling minimal',
    cells: [1, 1, 1, 1, -1, -1, 1, 1],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'house_tech_shuffle',
    subgenreId: 'house_tech',
    label: 'Shuffle groove',
    cells: [2, 1, -1, 2, 1, -1, 2, 1],
    gate: 0.68,
  ),
  ChordRhythmPreset(
    id: 'house_tech_after',
    subgenreId: 'house_tech',
    label: 'After-hours',
    cells: [-3, 1, -1, 1, -4, 1, -1],
    gate: 0.62,
  ),

  // Progressive house
  ChordRhythmPreset(
    id: 'house_prog_llsss',
    subgenreId: 'house_prog',
    label: 'Long·long·short×3',
    cells: [2, 2, 1, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'house_prog_rise',
    subgenreId: 'house_prog',
    label: 'Rising pulse',
    cells: [3, 2, 1, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'house_prog_build',
    subgenreId: 'house_prog',
    label: 'Build swell',
    cells: [2, 2, 2, 1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'house_prog_break',
    subgenreId: 'house_prog',
    label: 'Breakdown sustain',
    cells: [4, -2, 3, -1, 2, 1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'house_prog_euph',
    subgenreId: 'house_prog',
    label: 'Euphoric hits',
    cells: [2, -1, 2, -1, 1, 1, 1],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'house_prog_skip',
    subgenreId: 'house_prog',
    label: 'Progressive skip',
    cells: [-1, 2, -1, 1, -2, 1, 2],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'house_prog_332',
    subgenreId: 'house_prog',
    label: '3+3+2 house',
    cells: [3, 3, 2, 3, 3, 2],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'house_prog_climax',
    subgenreId: 'house_prog',
    label: 'Climax doubles',
    cells: [1, 1, 1, 1, 1, 1, 1, 1, -1, -1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'house_prog_waves',
    subgenreId: 'house_prog',
    label: 'Wave swell',
    cells: [4, 3, 2, 1, 1],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'house_prog_open',
    subgenreId: 'house_prog',
    label: 'Open pulse',
    cells: [2, -1, -1, 2, -1, -1, 1, 1],
    gate: 0.78,
  ),

  // Boom bap
  ChordRhythmPreset(
    id: 'hh_downbeat',
    subgenreId: 'hh_boombap',
    label: 'Downbeat hold',
    cells: [3, -1],
  ),
  ChordRhythmPreset(
    id: 'hh_chop8',
    subgenreId: 'hh_boombap',
    label: 'Chopped 1/8',
    cells: [1, -1, 1, 1, -1, 1, -1, 1],
  ),
  ChordRhythmPreset(
    id: 'hh_dusty',
    subgenreId: 'hh_boombap',
    label: 'Dusty skip',
    cells: [2, -1, 1, -2, 1, -1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'hh_sample',
    subgenreId: 'hh_boombap',
    label: 'Sample chop',
    cells: [1, 1, -2, 1, -1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'hh_nod',
    subgenreId: 'hh_boombap',
    label: 'Head-nod',
    cells: [2, 2, -1, 1, -1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'hh_pocket_rest',
    subgenreId: 'hh_boombap',
    label: 'Pocket rest',
    cells: [3, -2, 1, -1, 2],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'hh_swung',
    subgenreId: 'hh_boombap',
    label: 'Swung uneven',
    cells: [2, 1, 1, 2, 1, 1, -1],
    gate: 0.78,
  ),
  ChordRhythmPreset(
    id: 'hh_vamp',
    subgenreId: 'hh_boombap',
    label: 'Loop vamp',
    cells: [1, -1, 1, -1, 2, -2],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'hh_backbeat',
    subgenreId: 'hh_boombap',
    label: 'Backbeat gap',
    cells: [2, -1, -1, 2, -1, -1],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'hh_loop',
    subgenreId: 'hh_boombap',
    label: 'Loop repeat',
    cells: [1, 1, -1, -1, 1, 1, -1, -1],
    gate: 0.76,
  ),

  // Modern hip hop
  ChordRhythmPreset(
    id: 'hh_pocket',
    subgenreId: 'hh_modern',
    label: 'Syncop pocket',
    cells: [-1, 2, -1, 1, -2, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'hh_push',
    subgenreId: 'hh_modern',
    label: 'Push (anticipate)',
    cells: [-0.5, 1.5, -1, 1, -1, 1, -1, 1],
  ),
  ChordRhythmPreset(
    id: 'hh_trap_adj',
    subgenreId: 'hh_modern',
    label: 'Trap-adjacent roll',
    cells: [2, -2, 1, 1, 1, 1],
    gate: 0.65,
  ),
  ChordRhythmPreset(
    id: 'hh_melodic',
    subgenreId: 'hh_modern',
    label: 'Melodic rap bed',
    cells: [2, -1, 2, -1, 1, -1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'hh_stutter',
    subgenreId: 'hh_modern',
    label: 'Stutter short',
    cells: [1, 1, 1, -3, 1, 1, 1, -3],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'hh_space',
    subgenreId: 'hh_modern',
    label: 'Wide space',
    cells: [4, -2, 3, -3],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'hh_bounce',
    subgenreId: 'hh_modern',
    label: 'Bounce',
    cells: [-1, 1, 2, -1, -1, 1, 2],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'hh_soft',
    subgenreId: 'hh_modern',
    label: 'Soft stabs',
    cells: [1, -2, 1, -1, 2, -2],
    gate: 0.88,
  ),
  ChordRhythmPreset(
    id: 'hh_lazy',
    subgenreId: 'hh_modern',
    label: 'Lazy push',
    cells: [-2, 1, -1, 2, -2, 1, -1, 2],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'hh_triplet',
    subgenreId: 'hh_modern',
    label: 'Sparse triplet',
    cells: [2, 1, 1, -3, 2, 1, 1],
    gate: 0.72,
  ),

  // Trap main
  ChordRhythmPreset(
    id: 'trap_sparse',
    subgenreId: 'trap_main',
    label: 'Sparse + flurry',
    cells: [2, -2, 1, 1, 1, 1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'trap_roll16',
    subgenreId: 'trap_main',
    label: '16th roll',
    cells: [1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.55,
  ),
  ChordRhythmPreset(
    id: 'trap_dark',
    subgenreId: 'trap_main',
    label: 'Dark hold',
    cells: [3, -3, 1, -1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'trap_triplet',
    subgenreId: 'trap_main',
    label: 'Triplet 2+1+1',
    cells: [2, 1, 1, 2, 1, 1, -2],
    gate: 0.65,
  ),
  ChordRhythmPreset(
    id: 'trap_808',
    subgenreId: 'trap_main',
    label: '808 space',
    cells: [4, -3, 1, 1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'trap_rapid',
    subgenreId: 'trap_main',
    label: 'Rapid fire',
    cells: [1, 1, 1, 1, -2, 1, 1, 1],
    gate: 0.5,
  ),
  ChordRhythmPreset(
    id: 'trap_slide',
    subgenreId: 'trap_main',
    label: 'Slide gaps',
    cells: [2, -1, -1, 1, 1, 1, 1],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'trap_punch',
    subgenreId: 'trap_main',
    label: 'Punchy shorts',
    cells: [1, -1, 1, -1, 1, 1, 1, 1],
    gate: 0.55,
  ),
  ChordRhythmPreset(
    id: 'trap_ghost',
    subgenreId: 'trap_main',
    label: 'Ghost hits',
    cells: [1, -3, 1, 1, 1, -2],
    gate: 0.58,
  ),
  ChordRhythmPreset(
    id: 'trap_halfroll',
    subgenreId: 'trap_main',
    label: 'Half-bar roll',
    cells: [1, 1, 1, 1, -4, 1, 1, 1],
    gate: 0.52,
  ),

  // Trap half-time
  ChordRhythmPreset(
    id: 'trap_ht_hold',
    subgenreId: 'trap_halftime',
    label: 'Half-time hold',
    cells: [3, -1],
  ),
  ChordRhythmPreset(
    id: 'trap_ht_stabs',
    subgenreId: 'trap_halftime',
    label: 'Half-time stabs',
    cells: [1, -3, 1, -3],
  ),
  ChordRhythmPreset(
    id: 'trap_ht_snare',
    subgenreId: 'trap_halftime',
    label: 'Snare space',
    cells: [2, -4, 1, -3],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'trap_ht_menace',
    subgenreId: 'trap_halftime',
    label: 'Slow menace',
    cells: [2, -2, 2, -2],
    gate: 0.65,
  ),
  ChordRhythmPreset(
    id: 'trap_ht_double',
    subgenreId: 'trap_halftime',
    label: 'Double space',
    cells: [4, -4, 2, -4],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'trap_ht_silence',
    subgenreId: 'trap_halftime',
    label: 'Drop silence',
    cells: [1, -7, 1, -7],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'trap_ht_wide',
    subgenreId: 'trap_halftime',
    label: 'Wide punches',
    cells: [3, -2, 3, -2],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'trap_ht_crawl',
    subgenreId: 'trap_halftime',
    label: 'Crawl',
    cells: [1, -2, 1, -3, 1, -4],
    gate: 0.6,
  ),
  ChordRhythmPreset(
    id: 'trap_ht_echo',
    subgenreId: 'trap_halftime',
    label: 'Echo space',
    cells: [2, -5, 1, -5],
    gate: 0.72,
  ),
  ChordRhythmPreset(
    id: 'trap_ht_stagger',
    subgenreId: 'trap_halftime',
    label: 'Staggered hits',
    cells: [1, -1, 2, -4, 1, -1, 2],
    gate: 0.68,
  ),

  // Pop radio
  ChordRhythmPreset(
    id: 'pop_four',
    subgenreId: 'pop_radio',
    label: 'Four-square',
    cells: [1, 1, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'pop_sync',
    subgenreId: 'pop_radio',
    label: 'Syncop push',
    cells: [-1, 2, -1, 2, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'pop_verse',
    subgenreId: 'pop_radio',
    label: 'Verse chug',
    cells: [2, 2, 1, 1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'pop_chorus',
    subgenreId: 'pop_radio',
    label: 'Chorus lift',
    cells: [1, -1, 1, 1, 1, -1],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'pop_pre',
    subgenreId: 'pop_radio',
    label: 'Pre-chorus build',
    cells: [1, 1, 1, 1, -1, -1, -1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'pop_hook',
    subgenreId: 'pop_radio',
    label: 'Hook hits',
    cells: [2, -1, 2, -1, 1, 1],
    gate: 0.88,
  ),
  ChordRhythmPreset(
    id: 'pop_ballad',
    subgenreId: 'pop_radio',
    label: 'Ballad swell',
    cells: [4, -1, 3, -2],
    gate: 0.95,
  ),
  ChordRhythmPreset(
    id: 'pop_punch',
    subgenreId: 'pop_radio',
    label: 'Radio punch',
    cells: [1, 1, -1, 1, 1, 1, -1, 1],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'pop_eighth',
    subgenreId: 'pop_radio',
    label: 'Eighth offbeat',
    cells: [-1, 1, -1, 1, -1, 1, 1, -1],
    gate: 0.84,
  ),
  ChordRhythmPreset(
    id: 'pop_dropin',
    subgenreId: 'pop_radio',
    label: 'Drop-in hits',
    cells: [3, -1, 2, -2, 1, 1],
    gate: 0.86,
  ),

  // Pop anthem
  ChordRhythmPreset(
    id: 'pop_a_hold',
    subgenreId: 'pop_anthem',
    label: 'Anthem hold',
    cells: [3, 1],
  ),
  ChordRhythmPreset(
    id: 'pop_a_hit',
    subgenreId: 'pop_anthem',
    label: 'Anthem hits',
    cells: [2, -1, 2, -1],
  ),
  ChordRhythmPreset(
    id: 'pop_a_stadium',
    subgenreId: 'pop_anthem',
    label: 'Stadium',
    cells: [4, 4],
    gate: 0.95,
  ),
  ChordRhythmPreset(
    id: 'pop_a_arms',
    subgenreId: 'pop_anthem',
    label: 'Arms-up',
    cells: [2, 2, 1, 1, 1, 1],
    gate: 0.92,
  ),
  ChordRhythmPreset(
    id: 'pop_a_chorus',
    subgenreId: 'pop_anthem',
    label: 'Big chorus',
    cells: [1, 1, 1, 1, 2, 2],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'pop_a_bridge',
    subgenreId: 'pop_anthem',
    label: 'Bridge thin',
    cells: [2, -2, 1, -1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'pop_a_final',
    subgenreId: 'pop_anthem',
    label: 'Final chorus ×2',
    cells: [1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.88,
  ),
  ChordRhythmPreset(
    id: 'pop_a_shout',
    subgenreId: 'pop_anthem',
    label: 'Shout gaps',
    cells: [2, -1, -1, 2, -1, -1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'pop_a_double',
    subgenreId: 'pop_anthem',
    label: 'Double pump',
    cells: [2, 1, 2, 1, 2, 1],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'pop_a_sing',
    subgenreId: 'pop_anthem',
    label: 'Singalong gaps',
    cells: [4, -2, 2, -2, 2, -2],
    gate: 0.88,
  ),

  // R&B quiet storm
  ChordRhythmPreset(
    id: 'rnb_laid',
    subgenreId: 'rnb_quiet',
    label: 'Laid-back offbeat',
    cells: [-1, 2, -1, 2],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'rnb_slowjam',
    subgenreId: 'rnb_quiet',
    label: 'Slow-jam hold',
    cells: [4, -1, 3],
  ),
  ChordRhythmPreset(
    id: 'rnb_silky',
    subgenreId: 'rnb_quiet',
    label: 'Silky skip',
    cells: [-2, 1, -1, 2, -2],
    gate: 0.92,
  ),
  ChordRhythmPreset(
    id: 'rnb_pillow',
    subgenreId: 'rnb_quiet',
    label: 'Pillow',
    cells: [3, -2, 3, -2],
    gate: 0.95,
  ),
  ChordRhythmPreset(
    id: 'rnb_late',
    subgenreId: 'rnb_quiet',
    label: 'Late entry',
    cells: [-3, 2, -2, 2],
    gate: 0.88,
  ),
  ChordRhythmPreset(
    id: 'rnb_soft8',
    subgenreId: 'rnb_quiet',
    label: 'Soft 1/8',
    cells: [1, -2, 1, -2, 1, -2],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'rnb_breath',
    subgenreId: 'rnb_quiet',
    label: 'Breathy rests',
    cells: [2, -1, 2, -1, 2, -1],
    gate: 0.93,
  ),
  ChordRhythmPreset(
    id: 'rnb_warm',
    subgenreId: 'rnb_quiet',
    label: 'Warm pulse',
    cells: [1, -1, 2, -2, 1, -1],
    gate: 0.91,
  ),
  ChordRhythmPreset(
    id: 'rnb_velvet',
    subgenreId: 'rnb_quiet',
    label: 'Velvet entry',
    cells: [-4, 2, -3, 2, -4],
    gate: 0.94,
  ),
  ChordRhythmPreset(
    id: 'rnb_sigh',
    subgenreId: 'rnb_quiet',
    label: 'Sigh rests',
    cells: [2, -3, 2, -3, 2, -3],
    gate: 0.93,
  ),

  // R&B alt / neo
  ChordRhythmPreset(
    id: 'rnb_triplet',
    subgenreId: 'rnb_alt',
    label: 'Triplet feel',
    cells: [2, 1, 1, 2, 1, 1],
  ),
  ChordRhythmPreset(
    id: 'rnb_neo',
    subgenreId: 'rnb_alt',
    label: 'Neo pocket',
    cells: [-1, 1, 1, -2, 1, 1, -1],
  ),
  ChordRhythmPreset(
    id: 'rnb_jazzy',
    subgenreId: 'rnb_alt',
    label: 'Jazzy skip',
    cells: [-1, 1, -1, 2, 1, -1, 1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'rnb_lush',
    subgenreId: 'rnb_alt',
    label: 'Syncop lush',
    cells: [2, -1, 1, 1, -2, 1, 1],
    gate: 0.88,
  ),
  ChordRhythmPreset(
    id: 'rnb_broken',
    subgenreId: 'rnb_alt',
    label: 'Broken even',
    cells: [2, 2, 1, 1, 2, 1],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'rnb_bounce',
    subgenreId: 'rnb_alt',
    label: 'Neo bounce',
    cells: [-1, 2, 1, -1, 2, 1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'rnb_push',
    subgenreId: 'rnb_alt',
    label: 'Alt push',
    cells: [-1, 1, 2, -1, -1, 1, 2],
    gate: 0.83,
  ),
  ChordRhythmPreset(
    id: 'rnb_color',
    subgenreId: 'rnb_alt',
    label: 'Color rests',
    cells: [1, -1, 1, -3, 1, -1, 1],
    gate: 0.87,
  ),
  ChordRhythmPreset(
    id: 'rnb_float',
    subgenreId: 'rnb_alt',
    label: 'Floating triplets',
    cells: [2, 1, 1, -2, 2, 1, 1, -2],
    gate: 0.84,
  ),
  ChordRhythmPreset(
    id: 'rnb_midnight',
    subgenreId: 'rnb_alt',
    label: 'Midnight pocket',
    cells: [-2, 1, -1, 2, -2, 1, -1, 2],
    gate: 0.86,
  ),

  // Rock straight
  ChordRhythmPreset(
    id: 'rock_8ths',
    subgenreId: 'rock_straight',
    label: 'Straight 8ths',
    cells: [1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'rock_half',
    subgenreId: 'rock_straight',
    label: 'Half notes',
    cells: [2, 2],
  ),
  ChordRhythmPreset(
    id: 'rock_chug',
    subgenreId: 'rock_straight',
    label: 'Power chug',
    cells: [1, 1, 1, -1, 1, 1, 1, -1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'rock_verse',
    subgenreId: 'rock_straight',
    label: 'Verse downstroke',
    cells: [2, -1, 2, -1],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'rock_chorus',
    subgenreId: 'rock_straight',
    label: 'Chorus open',
    cells: [1, 1, 2, 2],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'rock_stop',
    subgenreId: 'rock_straight',
    label: 'Stop-time gaps',
    cells: [2, -2, -2, 2],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'rock_gallop',
    subgenreId: 'rock_straight',
    label: 'Gallop-ish',
    cells: [1, 1, 2, 1, 1, 2],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'rock_anthem',
    subgenreId: 'rock_straight',
    label: 'Anthem rock',
    cells: [4, -1, 4, -1],
    gate: 0.92,
  ),
  ChordRhythmPreset(
    id: 'rock_quarter',
    subgenreId: 'rock_straight',
    label: 'Quarter chug',
    cells: [1, -3, 1, -3, 1, -3, 1],
    gate: 0.83,
  ),
  ChordRhythmPreset(
    id: 'rock_halfbar',
    subgenreId: 'rock_straight',
    label: 'Half-bar punch',
    cells: [2, -2, -2, 2, -2, -2],
    gate: 0.78,
  ),

  // Rock drive
  ChordRhythmPreset(
    id: 'rock_drv_power',
    subgenreId: 'rock_drive',
    label: 'Driving power',
    cells: [1, 1, 1, -1, 1, 1, 1, -1],
  ),
  ChordRhythmPreset(
    id: 'rock_anticipate',
    subgenreId: 'rock_drive',
    label: 'Anticipation',
    cells: [-1, 3, -1, 3],
  ),
  ChordRhythmPreset(
    id: 'rock_punk',
    subgenreId: 'rock_drive',
    label: 'Punk 1/8',
    cells: [1, 1, 1, 1, 1, 1, 1, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'rock_gallop_m',
    subgenreId: 'rock_drive',
    label: 'Metal gallop',
    cells: [1, 1, 2, 1, 1, 2, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'rock_stomp',
    subgenreId: 'rock_drive',
    label: 'Stomp',
    cells: [2, 2, -1, -1, 2, 2],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'rock_palm',
    subgenreId: 'rock_drive',
    label: 'Palm-mute shorts',
    cells: [1, 1, -1, 1, 1, -1, 1, 1],
    gate: 0.55,
  ),
  ChordRhythmPreset(
    id: 'rock_ring',
    subgenreId: 'rock_drive',
    label: 'Chorus rings',
    cells: [2, 2, 2, 2],
    gate: 0.95,
  ),
  ChordRhythmPreset(
    id: 'rock_break',
    subgenreId: 'rock_drive',
    label: 'Breakdown hits',
    cells: [1, -3, 1, -3, 2, 2],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'rock_blast',
    subgenreId: 'rock_drive',
    label: 'Blast 16ths',
    cells: [1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1],
    gate: 0.58,
  ),
  ChordRhythmPreset(
    id: 'rock_riff',
    subgenreId: 'rock_drive',
    label: 'Riff syncopation',
    cells: [1, -1, 1, 1, -2, 1, -1, 1],
    gate: 0.72,
  ),

  // Reggae skank
  ChordRhythmPreset(
    id: 'reg_skank',
    subgenreId: 'reg_skank',
    label: 'Skank (offbeats)',
    cells: [-1, 1, -1, 1, -1, 1, -1, 1],
  ),
  ChordRhythmPreset(
    id: 'reg_onedrop',
    subgenreId: 'reg_skank',
    label: 'One-drop feel',
    cells: [-2, 1, -1, 1, -2, 1, -1],
  ),
  ChordRhythmPreset(
    id: 'reg_steppers',
    subgenreId: 'reg_skank',
    label: 'Steppers',
    cells: [1, 1, 1, 1, -1, -1, -1, -1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'reg_rockers',
    subgenreId: 'reg_skank',
    label: 'Rockers',
    cells: [2, -2, 1, -1, 2, -2],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'reg_bubble',
    subgenreId: 'reg_skank',
    label: 'Bubble',
    cells: [1, -1, 1, -1, 1, -1, 2, -2],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'reg_irie',
    subgenreId: 'reg_skank',
    label: 'Irie skip',
    cells: [-1, 1, 1, -2, -1, 1, 1],
    gate: 0.88,
  ),
  ChordRhythmPreset(
    id: 'reg_heavy',
    subgenreId: 'reg_skank',
    label: 'Heavy rests',
    cells: [-3, 1, -4, 1, -3, 1],
    gate: 0.9,
  ),
  ChordRhythmPreset(
    id: 'reg_dense',
    subgenreId: 'reg_skank',
    label: 'Skank dense',
    cells: [-1, 1, -1, 1, 1, -1, 1, -1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'reg_double',
    subgenreId: 'reg_skank',
    label: 'Double skank',
    cells: [-1, 1, 1, -1, -1, 1, 1, -1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'reg_nyah',
    subgenreId: 'reg_skank',
    label: 'Nyahbinghi rest',
    cells: [-4, 1, -3, 1, -4, 1],
    gate: 0.88,
  ),

  // Dancehall
  ChordRhythmPreset(
    id: 'reg_dh_stabs',
    subgenreId: 'reg_dancehall',
    label: 'Dancehall stabs',
    cells: [1, -2, 1, -1, 1, -2],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_dembow',
    subgenreId: 'reg_dancehall',
    label: 'Dembow 3+3+2',
    cells: [3, 3, 2, 3, 3, 2],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_toast',
    subgenreId: 'reg_dancehall',
    label: 'Toast gaps',
    cells: [2, -2, 1, -1, 1, 1],
    gate: 0.72,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_bash',
    subgenreId: 'reg_dancehall',
    label: 'Bashment',
    cells: [1, 1, -1, 1, 1, -1, 1, 1],
    gate: 0.65,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_digital',
    subgenreId: 'reg_dancehall',
    label: 'Digital dancehall',
    cells: [1, -1, 1, 1, -2, 1, -1],
    gate: 0.68,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_rapid',
    subgenreId: 'reg_dancehall',
    label: 'Rapid toast',
    cells: [1, 1, 1, 1, -2, 1, 1, 1],
    gate: 0.55,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_space',
    subgenreId: 'reg_dancehall',
    label: 'Space drops',
    cells: [3, -3, 1, -1, 2, -2],
    gate: 0.78,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_riddim',
    subgenreId: 'reg_dancehall',
    label: 'Riddim hit',
    cells: [2, 1, 1, 2, -2, 1, 1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_bounce',
    subgenreId: 'reg_dancehall',
    label: 'Riddim bounce',
    cells: [1, -1, 2, -1, 1, -1, 2, -1],
    gate: 0.68,
  ),
  ChordRhythmPreset(
    id: 'reg_dh_clash',
    subgenreId: 'reg_dancehall',
    label: 'Clash gaps',
    cells: [2, -3, 1, 1, -2, 1, 1],
    gate: 0.7,
  ),

  // Tresillo / Latin
  ChordRhythmPreset(
    id: 'lat_tresillo',
    subgenreId: 'lat_tresillo',
    label: 'Tresillo 3+3+2',
    cells: [3, 3, 2],
  ),
  ChordRhythmPreset(
    id: 'lat_cinquillo',
    subgenreId: 'lat_tresillo',
    label: 'Cinquillo',
    cells: [2, 1, 2, 1, 2],
  ),
  ChordRhythmPreset(
    id: 'lat_habanera',
    subgenreId: 'lat_tresillo',
    label: 'Habanera-ish',
    cells: [2, 1, 2, 2, 1, 2],
    gate: 0.85,
  ),
  ChordRhythmPreset(
    id: 'lat_montuno',
    subgenreId: 'lat_tresillo',
    label: 'Montuno pulse',
    cells: [2, 1, 2, 1, 2, 1, 2, 1],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'lat_on2',
    subgenreId: 'lat_tresillo',
    label: 'Salsa on-2',
    cells: [1, -1, 2, -1, 1, -1, 2, -1],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'lat_tumbao',
    subgenreId: 'lat_tresillo',
    label: 'Tumbao sketch',
    cells: [2, -1, 1, -1, 2, -1, 1, -1],
    gate: 0.78,
  ),
  ChordRhythmPreset(
    id: 'lat_afro',
    subgenreId: 'lat_tresillo',
    label: 'Afro-Cuban',
    cells: [3, 2, 2, 3, 2, 2],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'lat_syncop',
    subgenreId: 'lat_tresillo',
    label: 'Syncop dense',
    cells: [-1, 2, -1, 1, -2, 1, 2, -1],
    gate: 0.7,
  ),
  ChordRhythmPreset(
    id: 'lat_reggaeton',
    subgenreId: 'lat_tresillo',
    label: 'Reggaeton pulse',
    cells: [3, 3, 2, 3, 3, 2, -2],
    gate: 0.72,
  ),
  ChordRhythmPreset(
    id: 'lat_bomba',
    subgenreId: 'lat_tresillo',
    label: 'Bomba skip',
    cells: [2, -1, 1, 2, -1, 1, 2, -1],
    gate: 0.76,
  ),

  // Clave
  ChordRhythmPreset(
    id: 'lat_son',
    subgenreId: 'lat_clave',
    label: 'Son clave (2-3)',
    cells: [1, -1, 1, -2, 1, -1, 1, -1],
  ),
  ChordRhythmPreset(
    id: 'lat_rumba',
    subgenreId: 'lat_clave',
    label: 'Rumba feel',
    cells: [1, -2, 1, -1, 1, -1, 1, -1],
  ),
  ChordRhythmPreset(
    id: 'lat_son32',
    subgenreId: 'lat_clave',
    label: 'Son clave (3-2)',
    cells: [1, -1, 1, -1, 1, -2, 1, -1],
  ),
  ChordRhythmPreset(
    id: 'lat_mozambique',
    subgenreId: 'lat_clave',
    label: 'Mozambique-ish',
    cells: [2, 1, -1, 2, 1, -1, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'lat_guaguanco',
    subgenreId: 'lat_clave',
    label: 'Guaguancó sketch',
    cells: [1, -1, 2, -1, 1, -2, 1, -1],
    gate: 0.78,
  ),
  ChordRhythmPreset(
    id: 'lat_clave_rest',
    subgenreId: 'lat_clave',
    label: 'Clave + rests',
    cells: [1, -2, 1, -3, 1, -1, 1, -2],
    gate: 0.8,
  ),
  ChordRhythmPreset(
    id: 'lat_callresp',
    subgenreId: 'lat_clave',
    label: 'Call-response',
    cells: [2, -2, 1, -1, 2, -2, 1, -1],
    gate: 0.82,
  ),
  ChordRhythmPreset(
    id: 'lat_party',
    subgenreId: 'lat_clave',
    label: 'Party clave',
    cells: [1, 1, -1, 1, 1, -2, 1, 1],
    gate: 0.75,
  ),
  ChordRhythmPreset(
    id: 'lat_rumba_clave',
    subgenreId: 'lat_clave',
    label: 'Rumba clave',
    cells: [1, -2, 1, -1, 1, -1, 1, -2],
    gate: 0.77,
  ),
  ChordRhythmPreset(
    id: 'lat_timba',
    subgenreId: 'lat_clave',
    label: 'Timba dense',
    cells: [1, -1, 1, 1, -1, 1, -1, 1, 1],
    gate: 0.73,
  ),

  ChordRhythmPreset.sustained,
];
