part of 'project_snapshot.dart';

extension LfoSnapshotCopywithOperation on LfoSnapshot {
  LfoSnapshot copyWith({
    int? id,
    String? ownerDeviceId,
    String? type,
    int? retrigger,
    int? waveform,
    double? rate,
    int? syncDivision,
    double? phase,
    int? polarity,
    double? attack,
    double? decay,
    double? sustain,
    double? release,
    String? name,
    int? curveType,
    double? hold,
    double? delay,
    double? attackCurve,
    double? decayCurve,
    double? releaseCurve,
    int? analogMode,
    int? noteFollow,
    double? morph,
    double? spread,
    double? smoothing,
    int? sequencerSteps,
    int? sequencerDirection,
    int? sequencerShape,
    List<double>? stepValues,
    List<double>? curveBpPositions,
    List<double>? curveBpValues,
    List<int>? curveBpShapes,
  }) {
    return LfoSnapshot(
      id: id ?? this.id,
      ownerDeviceId: ownerDeviceId ?? this.ownerDeviceId,
      type: type ?? this.type,
      retrigger: retrigger ?? this.retrigger,
      waveform: waveform ?? this.waveform,
      rate: rate ?? this.rate,
      syncDivision: syncDivision ?? this.syncDivision,
      phase: phase ?? this.phase,
      polarity: polarity ?? this.polarity,
      attack: attack ?? this.attack,
      decay: decay ?? this.decay,
      sustain: sustain ?? this.sustain,
      release: release ?? this.release,
      name: name ?? this.name,
      curveType: curveType ?? this.curveType,
      hold: hold ?? this.hold,
      delay: delay ?? this.delay,
      attackCurve: attackCurve ?? this.attackCurve,
      decayCurve: decayCurve ?? this.decayCurve,
      releaseCurve: releaseCurve ?? this.releaseCurve,
      analogMode: analogMode ?? this.analogMode,
      noteFollow: noteFollow ?? this.noteFollow,
      morph: morph ?? this.morph,
      spread: spread ?? this.spread,
      smoothing: smoothing ?? this.smoothing,
      sequencerSteps: sequencerSteps ?? this.sequencerSteps,
      sequencerDirection: sequencerDirection ?? this.sequencerDirection,
      sequencerShape: sequencerShape ?? this.sequencerShape,
      stepValues: stepValues ?? this.stepValues,
      curveBpPositions: curveBpPositions ?? this.curveBpPositions,
      curveBpValues: curveBpValues ?? this.curveBpValues,
      curveBpShapes: curveBpShapes ?? this.curveBpShapes,
    );
  }
}
