#pragma once

#include <string>

namespace audioapp {

/// Serializable device DTO shared by project snapshots and device type factories.
struct DeviceState {
    std::string id;
    std::string type;
    float frequencyHz = 440.0f;
    float gain = 1.0f;
    float pan = 0.5f;
    std::string sampleId;
    float attack = 0.01f;
    float decay = 0.3f;
    float sustain = 0.7f;
    float release = 0.4f;
    float filterCutoff = 1.0f;
    float filterQ = 0.35f;
    int filterMode = 0;
    float trimStartSec = 0.0f;
    float trimEndSec = 0.0f;
    float regionStartSec = 0.0f;
    float regionEndSec = 0.0f;
    float rootPitch = 60.0f;
    float rootFineTune = 0.0f;
    int playbackMode = 0;
    bool bypassed = false;
    float osc1Shape = 0.5f;
    float osc2Shape = 0.5f;
    float osc1Octave = 0.5f;
    float osc1Semi = 0.0f;
    float osc1Detune = 0.5f;
    float osc2Octave = 0.5f;
    float osc2Semi = 0.0f;
    float osc2Detune = 0.5f;
    float oscMix = 0.37f;
    float osc1Sync = 0.0f;
    float osc2Sync = 0.0f;
    float noiseLevel = 0.0f;
    int oscMixMode = 0;
    float unisonVoices = 0.0f;
    float unisonDetune = 0.35f;
    float filterEnvAmount = 0.5f;
    float filterAttack = 0.05f;
    float filterDecay = 0.35f;
    float filterSustain = 0.4f;
    float filterRelease = 0.45f;
    float glideMs = 0.0f;
    float velocitySensitivity = 1.0f;
    float preHpCutoff = 0.0f;
    float preHpRes = 0.2f;
    float preDrive = 0.0f;
    float mixFeedback = 0.0f;
    float globalPitch = 0.5f;
    float filterKeyTrack = 0.0f;
    float filterDrive = 0.0f;
    float filterShaper = 0.0f;
    float filterFm = 0.0f;
    int filterShaperMode = 1;
    float synthLegato = 0.0f;
    float synthMono = 0.0f;
    // Bass Synth fields
    float bassOscShape = 0.3f;
    float bassSubMix = 0.5f;
    float bassNoise = 0.0f;
    float bassFilterResonance = 0.25f;
    float bassDrive = 0.0f;
    float bassSquash = 0.0f;
    float bassVelocitySense = 1.0f;
    int bassSubOctave = 0;
    int bassOctave = 2;
    float kickModel = 0.0f;
    float kickPitch = 0.55f;
    float kickPunch = 0.60f;
    float kickDecay = 0.50f;
    float kickClick = 0.35f;
    float kickTone = 0.50f;
    float kickVelocity = 1.0f;
    float kickKeyTrack = 1.0f;
    float snareModel = 0.0f;
    float snareBody = 0.45f;
    float snareRing = 0.40f;
    float snareTune = 0.50f;
    float snareSnares = 0.60f;
    float snareSnap = 0.40f;
    float snareDecay = 0.50f;
    float snareVelocity = 1.0f;
    float clapBursts = 0.50f;
    float clapSpread = 0.45f;
    float clapTone = 0.55f;
    float clapRoom = 0.50f;
    float clapDecay = 0.50f;
    float clapVelocity = 1.0f;
    float cymbalColor = 0.68f;
    float cymbalDecay = 0.50f;
    float cymbalWidth = 0.35f;
    float cymbalVelocity = 1.0f;
    float cymbalModel = 0.0f;
    float crashModel = 0.0f;
    float crashColor = 0.62f;
    float crashSpread = 0.50f;
    float crashDecay = 0.55f;
    float crashVelocity = 1.0f;
    float gateThreshold = 0.45f;
    float gateAttack = 0.25f;
    float gateRelease = 0.50f;
    float gateHold = 0.20f;
    float gateRange = 0.0f;
    float compThreshold = 0.55f;
    float compRatio = 0.50f;
    float compAttack = 0.20f;
    float compRelease = 0.55f;
    float compKnee = 0.25f;
    float compMakeup = 0.35f;
    float expandThreshold = 0.40f;
    float expandRatio = 0.45f;
    float expandAttack = 0.25f;
    float expandRelease = 0.55f;
    float expandRange = 0.15f;
    float limitCeiling = 0.85f;
    float limitAttack = 0.10f;
    float limitRelease = 0.40f;
    float limitKnee = 0.0f;
    float limitDrive = 0.0f;
    float limitMakeup = 0.0f;
    float inputGain = 1.0f;
};

} // namespace audioapp
