part of 'device_preset_store.dart';

const Map<String, DevicePreset> _hihat = {
  'preset:808-chh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.55, 'hihatDecay': 0.22, 'hihatTightness': 0.85, 'hihatNoise': 0.65, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:808-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.7, 'hihatTightness': 0.25, 'hihatNoise': 0.55, 'hihatWidth': 0.45, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:909-chh': DevicePreset(params: {'hihatPitch': 0.58, 'hihatColor': 0.6, 'hihatDecay': 0.2, 'hihatTightness': 0.88, 'hihatNoise': 0.7, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:909-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.55, 'hihatDecay': 0.62, 'hihatTightness': 0.3, 'hihatNoise': 0.6, 'hihatWidth': 0.5, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:electro-chh': DevicePreset(params: {'hihatPitch': 0.62, 'hihatColor': 0.65, 'hihatDecay': 0.18, 'hihatTightness': 0.9, 'hihatNoise': 0.75, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:electro-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.55, 'hihatTightness': 0.35, 'hihatNoise': 0.65, 'hihatWidth': 0.4, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:trap-chh': DevicePreset(params: {'hihatPitch': 0.65, 'hihatColor': 0.6, 'hihatDecay': 0.15, 'hihatTightness': 0.92, 'hihatNoise': 0.8, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:trap-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.75, 'hihatTightness': 0.2, 'hihatNoise': 0.5, 'hihatWidth': 0.55, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:boombap-chh': DevicePreset(params: {'hihatPitch': 0.48, 'hihatColor': 0.4, 'hihatDecay': 0.28, 'hihatTightness': 0.65, 'hihatNoise': 0.45, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:boombap-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.58, 'hihatTightness': 0.35, 'hihatNoise': 0.4, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:house-chh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.55, 'hihatDecay': 0.2, 'hihatTightness': 0.85, 'hihatNoise': 0.6, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:house-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.6, 'hihatTightness': 0.3, 'hihatNoise': 0.55, 'hihatWidth': 0.5, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:techno-chh': DevicePreset(params: {'hihatPitch': 0.6, 'hihatColor': 0.45, 'hihatDecay': 0.16, 'hihatTightness': 0.9, 'hihatNoise': 0.7, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:techno-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.5, 'hihatTightness': 0.35, 'hihatNoise': 0.55, 'hihatWidth': 0.4, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:pop-chh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.25, 'hihatTightness': 0.75, 'hihatNoise': 0.5, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:pop-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.55, 'hihatTightness': 0.35, 'hihatNoise': 0.45, 'hihatWidth': 0.4, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:rnb-chh': DevicePreset(params: {'hihatPitch': 0.5, 'hihatColor': 0.4, 'hihatDecay': 0.3, 'hihatTightness': 0.6, 'hihatNoise': 0.4, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:rnb-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.65, 'hihatTightness': 0.3, 'hihatNoise': 0.35, 'hihatWidth': 0.45, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:reggae-chh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.45, 'hihatDecay': 0.22, 'hihatTightness': 0.8, 'hihatNoise': 0.45, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:reggae-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.5, 'hihatTightness': 0.35, 'hihatNoise': 0.4, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:rock-chh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.45, 'hihatDecay': 0.28, 'hihatTightness': 0.7, 'hihatNoise': 0.4, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:rock-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.6, 'hihatTightness': 0.3, 'hihatNoise': 0.4, 'hihatWidth': 0.4, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:breakbeat-chh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.22, 'hihatTightness': 0.78, 'hihatNoise': 0.55, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:breakbeat-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.55, 'hihatTightness': 0.32, 'hihatNoise': 0.5, 'hihatWidth': 0.45, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:disco-chh': DevicePreset(params: {'hihatPitch': 0.58, 'hihatColor': 0.55, 'hihatDecay': 0.2, 'hihatTightness': 0.85, 'hihatNoise': 0.55, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:disco-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.58, 'hihatTightness': 0.3, 'hihatNoise': 0.5, 'hihatWidth': 0.5, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:dnb-chh': DevicePreset(params: {'hihatPitch': 0.62, 'hihatColor': 0.55, 'hihatDecay': 0.14, 'hihatTightness': 0.92, 'hihatNoise': 0.75, 'hihatWidth': 0.35, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:dnb-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.5, 'hihatDecay': 0.48, 'hihatTightness': 0.3, 'hihatNoise': 0.6, 'hihatWidth': 0.45, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:ambient-chh': DevicePreset(params: {'hihatPitch': 0.45, 'hihatColor': 0.35, 'hihatDecay': 0.4, 'hihatTightness': 0.45, 'hihatNoise': 0.3, 'hihatWidth': 0.5, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
  'preset:ambient-ohh': DevicePreset(params: {'hihatPitch': 0.55, 'hihatColor': 0.35, 'hihatDecay': 0.8, 'hihatTightness': 0.2, 'hihatNoise': 0.25, 'hihatWidth': 0.65, 'hihatVelocity': 1, 'hihatKeyTrack': 0}),
};
