part of 'subtractive_synth_presets.dart';

final Map<String, SubtractiveSynthPreset> _subtractive_presetsGroup2 = {
  'preset:synth-bass-wobble-talk': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.25,
      'osc2Shape': 0.5,
      'oscMix': 0.4,
      'osc1Octave': 0.32,
      'filterCutoff': 0.34,
      'filterQ': 0.55,
      'filterEnvAmount': 0.12,
      'attack': 0.02,
      'sustain': 0.88,
      'release': 0.25,
      'synthMono': 1.0,
      'synthLegato': 1.0,
      'glideMs': 0.03,
    },
    lfos: const [SubtractiveSynthPresets._halfSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.48),
      SubtractivePresetMod(lfoIndex: 0, paramId: 'osc1Detune', amount: 0.08),
    ],
  ),

  // ── Motion leads & FX (3) ───────────────────────────────────────────────
  'preset:synth-lead-wobble': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.5,
      'oscMix': 0.45,
      'filterCutoff': 0.62,
      'filterQ': 0.52,
      'filterEnvAmount': 0.35,
      'attack': 0.0,
      'decay': 0.2,
      'sustain': 0.75,
      'release': 0.2,
      'glideMs': 0.05,
    },
    lfos: const [SubtractiveSynthPresets._eighthSquare],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.45),
    ],
  ),
  'preset:synth-lead-siren': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.25,
      'oscMix': 0.6,
      'osc1Sync': 0.7,
      'filterCutoff': 0.55,
      'filterQ': 0.65,
      'filterEnvAmount': 0.2,
      'attack': 0.0,
      'sustain': 0.85,
      'release': 0.15,
      'glideMs': 0.08,
    },
    lfos: const [SubtractivePresetLfo(waveform: 2, syncDivision: 2, rate: 1.5)],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.52),
      SubtractivePresetMod(lfoIndex: 0, paramId: 'osc1Sync', amount: 0.18),
    ],
  ),
  'preset:synth-fx-riser-noise': SubtractiveSynthPresets._bundle(
    {
      'noiseLevel': 0.55,
      'oscMix': 0.08,
      'osc1Shape': 0.5,
      'filterCutoff': 0.22,
      'filterQ': 0.35,
      'filterEnvAmount': 0.4,
      'filterAttack': 0.0,
      'filterDecay': 0.8,
      'attack': 0.02,
      'decay': 0.6,
      'sustain': 0.3,
      'release': 0.5,
    },
    lfos: const [SubtractiveSynthPresets._barSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.62),
      SubtractivePresetMod(lfoIndex: 0, paramId: 'noiseLevel', amount: 0.2),
    ],
  ),

  // ── Pads (5) ──────────────────────────────────────────────────────────
  'preset:synth-pad-warm': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.12,
      'oscMix': 0.62,
      'unisonVoices': 0.66,
      'unisonDetune': 0.42,
      'filterCutoff': 0.52,
      'filterQ': 0.18,
      'filterEnvAmount': 0.38,
      'filterAttack': 0.18,
      'filterDecay': 0.55,
      'attack': 0.42,
      'decay': 0.35,
      'sustain': 0.88,
      'release': 0.72,
      'glideMs': 0.18,
      'synthLegato': 1.0,
      'velocitySensitivity': 0.7,
    },
    lfos: const [SubtractiveSynthPresets._quarterSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.24),
    ],
  ),
  'preset:synth-pad-glass': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.08,
      'osc2Shape': 0.25,
      'osc2Semi': 0.18,
      'oscMix': 0.55,
      'filterCutoff': 0.74,
      'filterQ': 0.1,
      'filterEnvAmount': 0.18,
      'attack': 0.55,
      'decay': 0.28,
      'sustain': 0.92,
      'release': 0.8,
      'velocitySensitivity': 0.55,
    },
    lfos: const [SubtractiveSynthPresets._halfTri],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.16),
    ],
  ),
  'preset:synth-pad-choir': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.5,
      'osc2Semi': 0.09,
      'oscMix': 0.5,
      'unisonVoices': 1.0,
      'unisonDetune': 0.58,
      'filterCutoff': 0.48,
      'filterQ': 0.22,
      'filterEnvAmount': 0.3,
      'filterAttack': 0.22,
      'filterDecay': 0.5,
      'attack': 0.48,
      'sustain': 0.9,
      'release': 0.85,
      'glideMs': 0.12,
      'synthLegato': 1.0,
    },
    lfos: const [SubtractiveSynthPresets._barSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.2),
      SubtractivePresetMod(lfoIndex: 0, paramId: 'unisonDetune', amount: 0.08),
    ],
  ),
  'preset:synth-pad-dark': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.75,
      'oscMix': 0.45,
      'osc1Octave': 0.42,
      'filterCutoff': 0.32,
      'filterQ': 0.35,
      'filterMode': 0,
      'filterEnvAmount': 0.45,
      'filterAttack': 0.35,
      'filterDecay': 0.62,
      'attack': 0.38,
      'decay': 0.4,
      'sustain': 0.85,
      'release': 0.78,
      'noiseLevel': 0.06,
    },
    lfos: const [SubtractiveSynthPresets._slowSaw],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.32),
    ],
  ),
  'preset:synth-pad-lofi': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.25,
      'osc2Shape': 0.5,
      'oscMix': 0.48,
      'noiseLevel': 0.12,
      'filterCutoff': 0.38,
      'filterQ': 0.42,
      'filterMode': 0,
      'filterEnvAmount': 0.28,
      'attack': 0.25,
      'decay': 0.45,
      'sustain': 0.8,
      'release': 0.55,
      'preDrive': 0.12,
      'velocitySensitivity': 0.65,
    },
    lfos: const [SubtractiveSynthPresets._eighthSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.22),
      SubtractivePresetMod(lfoIndex: 0, paramId: 'noiseLevel', amount: 0.06),
    ],
  ),
  'preset:synth-warm-pad': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.12,
      'oscMix': 0.62,
      'unisonVoices': 0.66,
      'unisonDetune': 0.42,
      'filterCutoff': 0.52,
      'filterQ': 0.18,
      'filterEnvAmount': 0.38,
      'filterAttack': 0.18,
      'filterDecay': 0.55,
      'attack': 0.42,
      'decay': 0.35,
      'sustain': 0.88,
      'release': 0.72,
      'glideMs': 0.18,
      'synthLegato': 1.0,
      'velocitySensitivity': 0.7,
    },
    lfos: const [SubtractiveSynthPresets._quarterSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.24),
    ],
  ),

  // ── Leads (5) ─────────────────────────────────────────────────────────
  'preset:synth-lead-saw': SubtractiveSynthPresets._bundle({
    'osc1Shape': 0.5,
    'osc2Shape': 0.5,
    'oscMix': 0.35,
    'filterCutoff': 0.82,
    'filterQ': 0.32,
    'filterEnvAmount': 0.58,
    'filterDecay': 0.28,
    'attack': 0.02,
    'decay': 0.22,
    'sustain': 0.72,
    'release': 0.25,
    'glideMs': 0.06,
  }),
};
