part of 'subtractive_synth_presets.dart';

final Map<String, SubtractiveSynthPreset> _subtractive_presetsGroup3 = {
  'preset:synth-lead-sync': SubtractiveSynthPresets._bundle({
    'osc1Shape': 0.5,
    'osc2Shape': 0.25,
    'oscMix': 0.62,
    'osc1Sync': 0.92,
    'osc2Octave': 0.62,
    'filterCutoff': 0.78,
    'filterQ': 0.48,
    'filterEnvAmount': 0.65,
    'filterAttack': 0.0,
    'filterDecay': 0.2,
    'attack': 0.0,
    'decay': 0.18,
    'sustain': 0.65,
    'release': 0.18,
    'glideMs': 0.05,
  }),
  'preset:synth-lead-silk': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.0,
      'osc2Shape': 0.12,
      'oscMix': 0.58,
      'osc2Semi': 0.36,
      'filterCutoff': 0.68,
      'filterQ': 0.12,
      'filterEnvAmount': 0.22,
      'attack': 0.12,
      'decay': 0.3,
      'sustain': 0.82,
      'release': 0.45,
      'velocitySensitivity': 0.75,
    },
    lfos: const [SubtractiveSynthPresets._barSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.14),
    ],
  ),
  'preset:synth-lead-wide': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.5,
      'oscMix': 0.48,
      'osc1Detune': 0.46,
      'osc2Detune': 0.54,
      'unisonVoices': 0.66,
      'unisonDetune': 0.55,
      'filterCutoff': 0.76,
      'filterQ': 0.25,
      'filterEnvAmount': 0.42,
      'attack': 0.03,
      'sustain': 0.78,
      'release': 0.32,
      'glideMs': 0.14,
      'synthLegato': 1.0,
    },
    lfos: const [SubtractivePresetLfo(waveform: 1, syncDivision: 4)],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'osc1Detune', amount: 0.1),
      SubtractivePresetMod(lfoIndex: 0, paramId: 'osc2Detune', amount: -0.1),
    ],
  ),
  'preset:synth-lead-bite': SubtractiveSynthPresets._bundle({
    'osc1Shape': 1.0,
    'osc2Shape': 0.75,
    'oscMix': 0.4,
    'oscMixMode': 1,
    'filterCutoff': 0.7,
    'filterQ': 0.52,
    'filterEnvAmount': 0.75,
    'filterAttack': 0.0,
    'filterDecay': 0.24,
    'filterDrive': 0.28,
    'attack': 0.0,
    'decay': 0.28,
    'sustain': 0.6,
    'release': 0.2,
    'preDrive': 0.18,
    'glideMs': 0.04,
  }),
};
