/// Factory preset parameter maps for subtractive_synth devices.
abstract final class SubtractiveSynthPresets {
  static const Map<String, Map<String, double>> presets = {
    'preset:synth-init': {
      'osc1Shape': 0.5,
      'osc2Shape': 0.5,
      'oscMix': 0.37,
      'filterCutoff': 0.75,
      'filterQ': 0.2,
      'attack': 0.02,
      'release': 0.35,
    },
    'preset:synth-warm-pad': {
      'osc1Shape': 0.5,
      'osc2Shape': 0.0,
      'oscMix': 0.65,
      'unisonVoices': 0.66,
      'unisonDetune': 0.4,
      'filterCutoff': 0.55,
      'filterEnvAmount': 0.35,
      'attack': 0.35,
      'release': 0.65,
      'glideMs': 0.15,
    },
    'preset:synth-pluck': {
      'osc1Shape': 0.5,
      'oscMix': 0.2,
      'filterCutoff': 0.85,
      'filterEnvAmount': 0.7,
      'filterAttack': 0.0,
      'filterDecay': 0.25,
      'attack': 0.0,
      'decay': 0.35,
      'sustain': 0.0,
      'release': 0.3,
    },
    'preset:synth-bass': {
      'osc1Shape': 0.75,
      'osc2Shape': 0.5,
      'oscMix': 0.35,
      'oscMixMode': 0,
      'filterCutoff': 0.45,
      'filterQ': 0.35,
      'attack': 0.01,
      'sustain': 0.9,
      'release': 0.25,
    },
    'preset:synth-lead': {
      'osc1Shape': 0.5,
      'osc2Shape': 0.5,
      'osc2Semi': 0.083,
      'oscMixMode': 2,
      'filterCutoff': 0.9,
      'filterEnvAmount': 0.55,
      'attack': 0.02,
      'release': 0.2,
      'glideMs': 0.12,
    },
    'preset:synth-noise-sweep': {
      'noiseLevel': 0.45,
      'oscMix': 0.0,
      'filterCutoff': 0.35,
      'filterEnvAmount': 0.85,
      'filterAttack': 0.1,
      'filterDecay': 0.6,
      'attack': 0.05,
      'release': 0.5,
    },
  };
}
