part of 'subtractive_synth_presets.dart';

final Map<String, SubtractiveSynthPreset> _subtractive_presetsGroup1 = {
  'preset:synth-init': SubtractiveSynthPresets._bundle({
    'osc1Shape': 0.5,
    'osc2Shape': 0.5,
    'oscMix': 0.37,
    'filterCutoff': 0.75,
    'filterQ': 0.2,
  }),
  'preset:synth-pluck': SubtractiveSynthPresets._bundle({
    'osc1Shape': 0.5,
    'oscMix': 0.2,
    'filterCutoff': 0.85,
    'filterEnvAmount': 0.7,
    'filterAttack': 0.0,
    'filterDecay': 0.25,
    'attack': 0.0,
    'decay': 0.35,
    'sustain': 0.0,
    'release': 0.3,
  }),
  'preset:synth-noise-sweep': SubtractiveSynthPresets._bundle(
    {
      'noiseLevel': 0.45,
      'oscMix': 0.0,
      'filterCutoff': 0.35,
      'filterEnvAmount': 0.85,
      'filterAttack': 0.1,
      'filterDecay': 0.6,
      'attack': 0.05,
      'release': 0.5,
    },
    lfos: const [SubtractivePresetLfo(waveform: 2, syncDivision: 4, rate: 2.0)],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.55),
    ],
  ),

  // ── Bass (5) ──────────────────────────────────────────────────────────
  'preset:synth-bass-sub-foundation': SubtractiveSynthPresets._bundle({
    'osc1Shape': 0.0,
    'osc2Shape': 0.0,
    'oscMix': 0.0,
    'osc1Octave': 0.25,
    'filterCutoff': 0.28,
    'filterQ': 0.15,
    'filterMode': 5,
    'filterEnvAmount': 0.15,
    'attack': 0.01,
    'decay': 0.2,
    'sustain': 0.95,
    'release': 0.3,
    'synthMono': 1.0,
    'velocitySensitivity': 0.85,
  }),
  'preset:synth-bass-punch': SubtractiveSynthPresets._bundle({
    'osc1Shape': 0.75,
    'osc2Shape': 1.0,
    'oscMix': 0.42,
    'osc1Octave': 0.32,
    'filterCutoff': 0.38,
    'filterQ': 0.45,
    'filterEnvAmount': 0.72,
    'filterAttack': 0.0,
    'filterDecay': 0.22,
    'filterSustain': 0.12,
    'attack': 0.0,
    'decay': 0.42,
    'sustain': 0.55,
    'release': 0.28,
    'synthMono': 1.0,
  }),
  'preset:synth-bass-reese': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.5,
      'oscMix': 0.55,
      'osc1Octave': 0.3,
      'osc1Detune': 0.42,
      'osc2Detune': 0.58,
      'unisonVoices': 1.0,
      'unisonDetune': 0.62,
      'filterCutoff': 0.32,
      'filterQ': 0.28,
      'filterMode': 0,
      'filterEnvAmount': 0.25,
      'attack': 0.04,
      'sustain': 0.88,
      'release': 0.4,
      'glideMs': 0.04,
    },
    lfos: const [SubtractiveSynthPresets._quarterSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.42),
    ],
  ),
  'preset:synth-bass-warehouse': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.75,
      'osc2Semi': 0.09,
      'oscMix': 0.68,
      'oscMixMode': 2,
      'osc1Octave': 0.28,
      'filterCutoff': 0.26,
      'filterQ': 0.55,
      'filterEnvAmount': 0.48,
      'filterFm': 0.35,
      'filterDecay': 0.48,
      'attack': 0.02,
      'decay': 0.35,
      'sustain': 0.8,
      'release': 0.35,
      'preDrive': 0.22,
      'synthMono': 1.0,
    },
    lfos: const [SubtractiveSynthPresets._eighthSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.18),
    ],
  ),
  'preset:synth-bass-acid': SubtractiveSynthPresets._bundle({
    'osc1Shape': 0.5,
    'osc2Shape': 0.5,
    'oscMix': 0.5,
    'osc1Sync': 0.85,
    'osc1Octave': 0.34,
    'filterCutoff': 0.22,
    'filterQ': 0.78,
    'filterEnvAmount': 0.92,
    'filterAttack': 0.0,
    'filterDecay': 0.18,
    'filterSustain': 0.0,
    'filterRelease': 0.12,
    'attack': 0.0,
    'decay': 0.15,
    'sustain': 0.0,
    'release': 0.08,
    'synthMono': 1.0,
    'synthLegato': 1.0,
    'glideMs': 0.02,
  }),

  // ── Wobble & motion bass (5) ────────────────────────────────────────────
  'preset:synth-bass-wobble-classic': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.75,
      'oscMix': 0.55,
      'osc1Octave': 0.28,
      'filterCutoff': 0.3,
      'filterQ': 0.72,
      'filterMode': 5,
      'filterEnvAmount': 0.08,
      'attack': 0.0,
      'decay': 0.18,
      'sustain': 0.92,
      'release': 0.22,
      'preDrive': 0.15,
      'synthMono': 1.0,
      'velocitySensitivity': 0.8,
    },
    lfos: const [SubtractiveSynthPresets._quarterSine],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.65),
    ],
  ),
  'preset:synth-bass-wobble-fast': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 1.0,
      'oscMix': 0.48,
      'osc1Octave': 0.3,
      'filterCutoff': 0.26,
      'filterQ': 0.68,
      'filterEnvAmount': 0.05,
      'attack': 0.0,
      'sustain': 0.95,
      'release': 0.15,
      'synthMono': 1.0,
    },
    lfos: const [SubtractiveSynthPresets._sixteenthTri],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.58),
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterQ', amount: 0.12),
    ],
  ),
  'preset:synth-bass-wobble-dub': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.5,
      'oscMix': 0.5,
      'osc1Octave': 0.26,
      'filterCutoff': 0.24,
      'filterQ': 0.75,
      'filterMode': 5,
      'filterEnvAmount': 0.0,
      'filterDrive': 0.18,
      'attack': 0.0,
      'decay': 0.12,
      'sustain': 0.98,
      'release': 0.1,
      'preDrive': 0.28,
      'synthMono': 1.0,
    },
    lfos: const [SubtractiveSynthPresets._eighthSquare],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.72),
    ],
  ),
  'preset:synth-bass-wobble-growl': SubtractiveSynthPresets._bundle(
    {
      'osc1Shape': 0.5,
      'osc2Shape': 0.75,
      'osc2Semi': 0.09,
      'oscMix': 0.62,
      'oscMixMode': 2,
      'osc1Octave': 0.27,
      'filterCutoff': 0.28,
      'filterQ': 0.62,
      'filterEnvAmount': 0.1,
      'filterFm': 0.2,
      'filterDrive': 0.22,
      'attack': 0.0,
      'sustain': 0.9,
      'release': 0.2,
      'preDrive': 0.32,
      'synthMono': 1.0,
    },
    lfos: const [
      SubtractiveSynthPresets._quarterSine,
      SubtractiveSynthPresets._eighthSine,
    ],
    mods: const [
      SubtractivePresetMod(lfoIndex: 0, paramId: 'filterCutoff', amount: 0.55),
      SubtractivePresetMod(lfoIndex: 1, paramId: 'filterFm', amount: 0.38),
      SubtractivePresetMod(lfoIndex: 1, paramId: 'filterDrive', amount: 0.15),
    ],
  ),
};
