part of 'library_midi_patterns.dart';

/// Factory drum beats — electro / pop / house.
final Map<String, LibraryMidiPattern> _library_midi_patternsGroupDrums_electro_pop_house = {
  "electro-1982-part1": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---------", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx", 39: "x---x-x-----x---", 44: "xx-x--xx------xx"}),
  "electro-808-crew-demo": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---------", 37: "----x-------x---", 38: "xxxxxxxxxxxx-xxx", 39: "----------x-x---", 44: "--xx--x---------"}),
  "electro-circuit-breaker": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "--x---xx--x----x", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx", 40: "x-x-xx-xx-xxxxxx", 41: "x---------------", 47: "x---------------"}),
  "electro-fast-lane": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---------", 38: "x-xxx-xxx-xxxxxx", 41: "xx-------x------", 44: "x-----x---------"}),
  "electro-freestyle-dont-stop": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---------", 37: "----x-------x---", 38: "x-xxx-xxx-xx-xxx", 44: "x--xx--x-xx-x--x"}),
  "electro-jj-fad-supersonic": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---x---x-", 37: "----x-------x---", 38: "x-xxx-xxx-xxx-xx"}),
  "electro-man-parrish-clap": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {40: "x-------x-------"}),
  "electro-miami-bass-classic": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-----x---x---x-", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "electro-miami-bass-syncop": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x--x-x-x-x------", 37: "----x-------x---", 38: "x-x-x-x-x-x-xxxx", 40: "------x------xxx"}),
  "electro-miami-mami-clave": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-----x---------", 37: "----x-------x---", 44: "x-xxx-xxx-xxx-xx"}),
  "electro-planet-rock-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---------", 37: "----x-------x---", 38: "x-xxx-xxx-xx-xxx", 40: "----x-------x---"}),
  "electro-planet-rock-cowbell": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---------", 37: "----x-------x---", 38: "x-xxx-xxx-xxxxxx", 44: "x-x-x-xx-x-xx-x-"}),
  "electro-robotnick-four": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "--x---x---x---x-", 40: "-x-x-x-x--x-x-x-"}),
  "electro-robotnick-problemes": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "xxxxx---x---x---", 37: "----x-------x---", 38: "--x---x---x---x-"}),
  "electro-shadow-groove": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "xxx---xx--xx--x-", 37: "----x-------x---", 38: "x-x-x-xxxx-xxx-x", 40: "x-xx--xx-x-xx-xx"}),
  "electro-south-i95": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-----xx--x----x", 37: "----x-------x---", 38: "x-x-x-x-x---x-x-", 39: "----------x-x---"}),
  "electro-xray-video-control": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---x--x--", 38: "x-xxxx-xx-xxxx--", 44: "x-x-x--x-xxx-x--"}),
  "house-909-basic1": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "x---x---x---x---", 39: "--x---x---x---x-", 40: "-x--x---------x-", 41: "---x------------", 43: "---x------------"}),
  "house-afro-house": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x---x---x---x---", 38: "x-x--x-x-x-x--x-", 40: "----x-------x---", 41: "------x-------x-", 44: "-x-x--x--x-x--x-"}),
  "house-brit-skip": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx", 39: "--x--x----x--x--"}),
  "house-deep-sparse": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---x---x---x---", 38: "x---x---x---x---", 39: "------x-------x-", 40: "----x-------x---"}),
  "house-disco-strings-bed": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 39: "--x---x---x---x-", 46: "x---x---x---x---"}),
  "house-four-on-floor-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 39: "--x---x---x---x-", 40: "----x-------x---"}),
  "house-french-filter": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 39: "--x---x---x---x-", 40: "----x-------x---", 41: "------------x---"}),
  "house-garage-2step": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.08, voices: {36: "x-------x--x----", 37: "----x-------x---", 38: "x--xx-x--xx-x--x", 39: "------x-------x-"}),
  "house-jacking-chicago": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "--x---x---x---x-", 40: "x---x---x---x---"}),
  "house-minimal-click": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "-x-x-x-x-x-x-x-x", 40: "----x---x---x---"}),
  "house-ni-swung": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x---x---x---x---", 37: "---------------x", 38: "x-x-x-x-x-x-x-x-", 39: "--x---x---x---x-", 40: "----x-------x---"}),
  "house-offbeat-bass-kick": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---x--.x---x--.", 38: "x-x-x-x-x-x-x-x-", 39: "--x---x---x---x-", 40: "----x-------x---"}),
  "house-progressive-build": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "xxxxxxxxxxxxxxxx", 40: "----x-------x---", 47: "x---------------"}),
  "house-rim-latin": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 40: "--x-xx----x-xx--", 44: "x--x--x--x--x--x"}),
  "house-tech-house-perc": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 40: "----x-x-----x-x-", 44: "--x--x----x--x--"}),
  "house-vocal-chop-space": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 39: "--------------x-", 40: "----x-----------"}),
  "pop-acoustic-campfire": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-------x-------", 38: "x---x---x---x---", 40: "----x-------x---"}),
  "pop-ballad-sparse": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---------------", 37: "--------x-------", 46: "x---x---x---x---"}),
  "pop-clap-layer": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x---x---", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx", 40: "----x-------x---"}),
  "pop-dancehall-lite": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x-----x-x---", 37: "----x--x----x---", 38: "x-x-x-x-x-x-x-x-"}),
  "pop-double-chorus-kick": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x--x----x--x----", 37: "----x-------x---", 38: "X-X-X-X-X-X-X-X-", 47: "x---------------"}),
  "pop-four-floor-anthem": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 39: "--x---x---x---x-", 40: "----x-------x---"}),
  "pop-half-time-chorus": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---------------", 37: "--------x-------", 38: "x-x-x-x-x-x-x-x-"}),
  "pop-money-beat-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "pop-money-beat-16hats": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "X.X.X.X.X.X.X.X."}),
  "pop-ohh-lift": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "x-x-x-x-x-x-x---", 39: "--------------x-"}),
  "pop-quiet-loud-verse": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----------x---", 37: "----x-------x---", 38: "x---x---x---x---"}),
  "pop-reggaeton-crossover": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x-----x-----", 37: "----x--x----x---", 38: "--x---x---x---x-"}),
  "pop-sidechain-pump": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 38: "-x-x-x-x-x-x-x-x", 40: "----x-------x---"}),
  "pop-syncop-kick": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x--x----x-x-----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "pop-tom-fill-lite": LibraryMidiPatterns._drumBeat(bars: 2, swingDelay: 0.0, voices: {36: "x-------x-------x---------------", 37: "----x-------x-------x-----------", 38: "x-x-x-x-x-x-x-x-x-x-x-x---------", 41: "------------------------------xx", 42: "--------------------------x-x---", 43: "------------------------x-x-----"}),
  "pop-uk-garage-shuffle": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-----x---x-----", 37: "----x-------x---", 38: "x--x--x--x--x--x", 39: "------x-------x-"}),
};
