part of 'library_midi_patterns.dart';

/// Factory drum beats — rnb / reggae / rock.
final Map<String, LibraryMidiPattern> _library_midi_patternsGroupDrums_rnb_reggae_rock = {
  "reggae-copeland-upbeat": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "--------x-------", 37: "----x-------x---", 38: "-X-X-X-X-X-X-X-X"}),
  "reggae-dancehall-dembow": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x-----x-----", 37: "----x--x----x---", 38: "x-x-x-x-x-x-x-x-"}),
  "reggae-dancehall-fast": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x--x----x---", 38: "--x---x---x---x-"}),
  "reggae-dub-sparse": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "--------x-------", 38: "------x-------x-", 40: "--------x-------", 44: "x---------------"}),
  "reggae-nyahbinghi-perc": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "--------x-------", 40: "--------x-------", 41: "--x---x---x---x-", 44: "x---x---x---x---"}),
  "reggae-one-drop-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "--------x-------", 38: "--x---x---x---x-", 40: "--------x-------"}),
  "reggae-one-drop-8hats": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "--------x-------", 38: "x-x-x-x-x-x-x-x-", 40: "--------x-------"}),
  "reggae-one-drop-rim-and": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "--------x-------", 38: "--x---x---x---x-", 40: "--------x-----x-"}),
  "reggae-one-drop-shuffle": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.08, voices: {36: "--------x-------", 38: "x--xx-x--xx-x--x", 40: "--------x-------"}),
  "reggae-rockers-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 40: "----x-------x---"}),
  "reggae-rockers-money": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "reggae-ska-half": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "--------x-------", 37: "--------x-------", 38: "x-x-x-x-x-x-x-x-"}),
  "reggae-steppers-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 40: "--------x-------"}),
  "reggae-steppers-8th-kick": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-x-x-x-x-x-x-x-", 38: "--x---x---x---x-", 40: "--------x-------"}),
  "reggae-steppers-tom": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---x---x---x---", 38: "x-x-x-x-x-x-x-x-", 40: "--------x-------", 41: "--------------x-", 42: "------------x---"}),
  "reggae-sublime-hybrid": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "--x---x---x---x-"}),
  "rnb-6-8-feel": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.08, voices: {36: "x-----x-----x---", 38: "x--x--x--x--x--x", 40: "----x-------x---"}),
  "rnb-alt-rnb-broken": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x----x---x--x---", 37: "---x-----x--x---", 38: "x-x--x-x--x-x-x-"}),
  "rnb-bounce-2000s": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x--x--x---x-----", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx", 39: "------x-------x-"}),
  "rnb-clap-delay": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-------x--x----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 40: "-----x-------x--"}),
  "rnb-classic-backbeat": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-------x--x----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "rnb-contemporary-trap": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----------x---", 37: "--------x-------", 38: "x-x-x-xxx-x-x-x-", 40: "--------x-------"}),
  "rnb-finger-snap": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x---------------", 38: "----x-------x---", 40: "----x-------x---"}),
  "rnb-gospel-chops": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x--x--x-x--x----", 37: "----X--.X--.X--.", 38: "x-x-x-x-x-x-x-x-", 47: "x---------------"}),
  "rnb-motown-four": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 41: "------------x---"}),
  "rnb-neo-soul-ghosts": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.08, voices: {36: "x--x----x-------", 37: "----X--.----X--.", 38: "x-x-x-x-x-x-x---", 39: "--------------x-"}),
  "rnb-neo-soul-rim": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.08, voices: {36: "x-----x---x-----", 37: "------.-------.-", 38: "x-x-x-x-x-x-x-x-", 40: "----x-------x---"}),
  "rnb-new-jack-swing": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.08, voices: {36: "x--x----x--x----", 37: "----x-------x---", 38: "x--xx-x--xx-x--x", 40: "----x-------x---"}),
  "rnb-philly-soul": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-------x-------", 37: "----x-------x---", 46: "x-x-x-x-x-x-x-x-"}),
  "rnb-slow-jam": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x-----------x---", 37: "--------x-------", 38: "x---x---x---x---", 39: "--------------x-"}),
  "rnb-timbaland-skip": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x--x------x--x--", 37: "----x--x----x---", 38: "x--x--x--x--x--x", 44: "------x-------x-"}),
  "rnb-verse-kick-hole": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-----------x---", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 39: "----------x-----"}),
  "rock-basic-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "rock-blues-shuffle": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.08, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "x--x--x--x--x--x"}),
  "rock-cypress-kick": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x--x----x-x-----", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx"}),
  "rock-fill-bar": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---------------", 37: "----x---xxxx----", 41: "--------------xx", 42: "------------xx--", 43: "--------xxxx----", 47: "x---------------"}),
  "rock-four-on-floor": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "rock-garage": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "X-X-X-X-X-X-X-X-", 47: "x-------x-------"}),
  "rock-half-time": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---------------", 37: "--------x-------", 38: "x-x-x-x-x-x-x-x-"}),
  "rock-hard-ni": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x--.----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "rock-metal-double": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "xx--xx--xx--xx--", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 47: "x---------------"}),
  "rock-pocket-ops-1": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x------xx--x----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 47: "x---------------"}),
  "rock-punk-01": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx"}),
  "rock-punk-dbeat": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x--x----x--x----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "rock-ride-chorus": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x--x----", 37: "----x-------x---", 46: "x-x-x-x-x-x-x-x-", 47: "x---------------"}),
  "rock-surf": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "----x--x----x--x", 38: "x-x-x-x-x-x-x-x-"}),
  "rock-tom-groove": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "----x-------x---", 38: "----------------", 41: "x---x---x---x---", 42: "--x---x---x---x-"}),
  "rock-train-beat": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x---x---x---", 37: "x-x-x-x-x-x-x-x-", 38: "----------------"}),
};
