part of 'library_midi_patterns.dart';

/// Factory drum beats — breakbeat / trap.
final Map<String, LibraryMidiPattern> _library_midi_patternsGroupDrums_breakbeat_trap = {
  "breakbeat-2step-break": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-----x---x-----", 37: "----x-------x---", 38: "x--x-xx--x-xx--x"}),
  "breakbeat-amen-bar3": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---------x-----", 37: "----x--x-x----x-", 46: "x-x-x-x-x-x-x-x-"}),
  "breakbeat-amen-bar4": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "--xx------------", 37: "-x--x--x-x----x-", 39: "----------x-----", 46: "x-x-x-x-x---x-x-", 47: "----------x-----"}),
  "breakbeat-amen-bars12": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---------xx----", 37: "----x--x-x--x--.", 46: "x-x-x-x-x-x-x-x-"}),
  "breakbeat-apache-perc": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x--x----", 37: "----x-------x---", 41: "--x---x---x---x-", 44: "x-xx-xx-x-xx-xx-"}),
  "breakbeat-big-beat": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x--x----x--x----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 47: "x-------x-------"}),
  "breakbeat-electro-break": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x--x--x---", 37: "----x-------x---", 38: "xxxxxxxxxxxxxxxx", 44: "x--x--xx--x--x--"}),
  "breakbeat-fill-snare": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---------------", 37: "--x-x-x-x-x-x-xx", 47: "--------------x-"}),
  "breakbeat-funky-drummer-lite": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-------x-------", 37: "----X.x.X.x.X.x.", 38: "x-x-x-x-x-x-x---", 39: "--------------x-"}),
  "breakbeat-ghost-snare-bed": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-------x--x----", 37: ".--.X--..--.X--.", 38: "x-x-x-x-x-x-x-x-"}),
  "breakbeat-half-amen": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---------xx----", 37: "----x--x-x--x---", 38: "x-x-x-x-x-x-x-x-"}),
  "breakbeat-hiphop-break": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x-----x---x-----", 37: "----x-------x---", 38: "x-x-x-x-x-x-x--x"}),
  "breakbeat-impeach-lite": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x--x----x-------", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "breakbeat-jungle-amen-chop": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x----x----", 37: "--x-x----x--x-x-", 38: "x-x-x-x-x-x-x-x-"}),
  "breakbeat-rolling": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x--x--x--x--x--x", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-"}),
  "breakbeat-think-feel": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.055, voices: {36: "x--x----x-------", 37: "----x-------x---", 38: "x-x-x-x-x-x-x-x-", 44: "------x-------x-"}),
  "trap-16th-hats": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "--------x-------", 38: "X.X.X.X.X.X.X.X."}),
  "trap-basic-half-time": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----------x---", 37: "--------x-------", 38: "x-x-x-x-x-x-x-x-", 40: "--------x-------"}),
  "trap-busy-kick": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x--x--x---x--x--", 37: "--------x-------", 38: "x-x-x-xxx-x-xxx-"}),
  "trap-clap-only-3": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x--x--------x---", 38: "xxxxxxxxxxxxxxxx", 40: "--------x-------"}),
  "trap-double-time-hats": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---x-----", 37: "--------x-------", 38: "xxxxxxxxxxxxxxxx", 39: "--------------x-"}),
  "trap-march-hats": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----------x---", 37: "--------x-------", 38: "X-x-X-x-X-x-X-x-"}),
  "trap-ni-2bar": LibraryMidiPatterns._drumBeat(bars: 2, swingDelay: 0.0, voices: {36: "x-----------x-------x-----------", 37: "----------------------------x-x-", 38: "x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-", 40: "--------x---------------x-------"}),
  "trap-open-hat-offs": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----------x---", 37: "--------x-------", 38: "x-x-x-x-x-x-x-x-", 39: "--x---x---x---x-"}),
  "trap-phonk": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---x-----x-----", 37: "----x-------x---", 38: "--x---x---x---x-", 44: "x-x-x-x-x-x-x-x-"}),
  "trap-pluggnb": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.03, voices: {36: "x---------x-----", 37: "--------x-------", 38: "x--x--x--x--x--x", 40: "--------.-------"}),
  "trap-pocket-ops-a": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x-----x---", 37: "--------x-------", 38: "x-x-x-x-x-x-x-x-"}),
  "trap-roll-end": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---------------", 37: "--------x-------", 38: "x-x-x-x-xxx-x-x-"}),
  "trap-snare-roll-end": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x---------------", 37: "--------x--xxxxx", 38: "x-x-x-x-x-------"}),
  "trap-sparse-drill": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x----x----", 37: "--------x-------", 38: "x---x---x---x---", 44: "------x-------x-"}),
  "trap-syncop-snare": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-------x-------", 37: "------x-----x---", 38: "x-x-xxx-x-x-xxx-"}),
  "trap-triplet-hats": LibraryMidiPatterns._drumBeat(bars: 1, swingDelay: 0.0, voices: {36: "x-----x---------", 37: "--------x-------", 38: "x--x--x--x--x--x", 39: "------x-------x-"}),
};
